<?php

return [
    'default_locale' => 'en',

    'locales' => [
        'en' => [
            'label' => 'EN',
            'name' => 'English',
        ],
        'de' => [
            'label' => 'DE',
            'name' => 'Deutsch',
        ],
    ],

    'socials' => [
        'email' => [
            'label' => 'Email',
            'display' => 'info@jeremylaederach.ch',
            'url' => 'mailto:info@jeremylaederach.ch',
        ],
        'github' => [
            'label' => 'GitHub',
            'display' => 'github.com/jeremylaederach',
            'url' => 'https://github.com/jeremylaederach',
        ],
        'linkedin' => [
            'label' => 'LinkedIn',
            'display' => 'Jeremy Läderach',
            'url' => 'https://www.linkedin.com/in/jeremy-l%C3%A4derach-816ab5326/',
        ],
    ],

    'content' => [
        'en' => [
            'meta' => [
                'title' => 'Jeremy Läderach',
                'description' => 'Personal portfolio of Jeremy Läderach, a software engineer building practical web systems with Laravel, .NET, and Angular.',
            ],
            'ui' => [
                'skip' => 'Skip to content',
                'language' => 'Language',
                'menu' => 'Primary navigation',
                'brand' => 'Jeremy Läderach home',
                'role' => 'Software Engineer',
                'open' => 'Open',
                'footer_navigation' => 'Explore',
                'legal_navigation' => 'Legal and external links',
                'back_to_top' => 'Back to top',
                'sound_mute' => 'Mute interface sounds',
                'sound_enable' => 'Enable interface sounds',
                'project_media' => 'Project views',
                'carousel' => 'carousel',
                'media_previous' => 'Previous view',
                'media_next' => 'Next view',
                'media_view' => 'View',
                'next_project' => 'Next project',
            ],
            'nav' => [
                ['label' => 'Home', 'route' => 'home', 'icon' => 'home'],
                ['label' => 'Projects', 'route' => 'projects', 'icon' => 'folder'],
                ['label' => 'About', 'route' => 'about', 'icon' => 'user'],
                ['label' => 'Contact', 'route' => 'contact', 'icon' => 'mail'],
            ],
            'home' => [
                'statement' => 'I build',
                'statement_accent' => 'useful digital systems.',
                'summary' => 'Architecting and engineering software that makes complex ideas feel simple.',
                'explore' => 'Explore projects',
                'index_label' => 'Landing',
                'routes' => [
                    [
                        'label' => 'Projects',
                        'description' => 'Products, migrations, and client work.',
                        'route' => 'projects',
                    ],
                    [
                        'label' => 'About me',
                        'description' => 'Background, experience, and the tools behind my work.',
                        'route' => 'about',
                    ],
                    [
                        'label' => 'Contact',
                        'description' => 'A direct line for focused collaboration.',
                        'route' => 'contact',
                    ],
                ],
            ],
            'about_page' => [
                'eyebrow' => 'Profile',
                'heading' => 'About me',
                'intro' => 'I\'m Jeremy, a software developer from Zurich. I build products across the full stack—from C# backends to product interfaces and deployment.',
                'story_link' => 'In brief',
                'story_heading' => 'In brief.',
                'story_current' => 'Right now I am building full-stack software and my own products: Quantified with Angular, ASP.NET Core, and PostgreSQL; SessionDeck as a native .NET app; and the Laravel systems behind Jay-Jay.',
                'story_notes' => [
                    [
                        'label' => 'Foundation',
                        'value' => 'My foundation is a four-year apprenticeship as an Application Developer EFZ at EcoLogic AG. It taught me to turn requirements into software that stays clear and maintainable in everyday use.',
                    ],
                    [
                        'label' => 'From September 2026',
                        'value' => 'I start the BSc in Business Informatics at OST—the next step between software, product, and business.',
                    ],
                ],
                'playground_label' => 'Code',
                'playground_heading' => 'Playground.',
                'playground_intro' => 'Three small demos in plain JavaScript. Change the input and watch the work happen.',
                'playground' => [
                    'sorting' => [
                        'title' => 'Sorting',
                        'run' => 'Start',
                        'shuffle' => 'Mix',
                        'metric' => 'Comparisons',
                        'complete' => 'Sorted',
                        'algorithms' => [
                            'quick' => [
                                'label' => 'Quick',
                                'description' => 'Chooses a pivot, then moves smaller values left and larger values right. It repeats that split until every group is in order.',
                            ],
                            'merge' => [
                                'label' => 'Merge',
                                'description' => 'Keeps splitting the list, then joins the pieces in order. The merge step rebuilds one sorted list from the smallest pieces.',
                            ],
                            'insertion' => [
                                'label' => 'Insertion',
                                'description' => 'Takes one value and inserts it into the part that is already sorted. The ordered section grows one bar at a time.',
                            ],
                            'selection' => [
                                'label' => 'Selection',
                                'description' => 'Finds the smallest remaining value and moves it to the front. Each pass locks one more bar into its final position.',
                            ],
                            'bubble' => [
                                'label' => 'Bubble',
                                'description' => 'Compares neighbours and swaps them when they are out of order. A pass without a swap means the list is finished.',
                            ],
                        ],
                    ],
                    'network' => [
                        'title' => 'Neural Network',
                        'description' => 'Draw a 0, 1 or 2. Every square becomes a number; three outputs compare the pattern and the strongest answer wins.',
                        'run' => 'Recognize',
                        'reset' => 'Clear',
                        'metric' => 'Guess',
                        'empty' => 'Draw a digit first',
                        'default' => '2',
                        'keyboard_note' => 'Use the arrow keys to move through the pixels. Press Space or Enter to switch one on or off.',
                        'visual' => [
                            'input' => 'Pixels',
                            'output' => 'Result',
                            'pixel' => 'Pixel',
                            'on' => 'on',
                            'off' => 'off',
                        ],
                        'presets' => [
                            '0' => ['label' => '0'],
                            '1' => ['label' => '1'],
                            '2' => ['label' => '2'],
                        ],
                    ],
                    'pathfinding' => [
                        'title' => 'Pathfinder',
                        'description' => 'Edit the walls, choose how the search should work, and compare the routes.',
                        'strategies' => [
                            'shortest' => [
                                'label' => 'Shortest',
                                'description' => 'Checks outwards from A and guarantees the fewest steps.',
                            ],
                            'guided' => [
                                'label' => 'Fewer checks',
                                'description' => 'Uses the distance to B, usually checks fewer cells, and still finds a shortest route.',
                            ],
                            'straight' => [
                                'label' => 'Fewer turns',
                                'description' => 'Prefers a straighter route, even when it needs a few extra steps.',
                            ],
                        ],
                        'keyboard_note' => 'Use the arrow keys to move across the grid. Press Space or Enter to block or open a cell.',
                        'run' => 'Find path',
                        'reset' => 'Reset',
                        'metric' => 'Checked · steps · turns',
                        'no_path' => 'No open path',
                        'visual' => [
                            'checked' => 'checked',
                            'steps' => 'steps',
                            'turns' => 'turns',
                            'cell' => 'Cell',
                            'blocked' => 'blocked',
                            'open' => 'open',
                            'start' => 'Start',
                            'goal' => 'Goal',
                            'fixed' => 'cannot be blocked',
                        ],
                    ],
                ],
                'technology_heading' => 'Stack',
                'technology_label' => 'Tools',
                'technology_intro' => 'The stack I actually work with—not every technology I have ever touched.',
                'technology_groups' => [
                    [
                        'title' => '.NET & C#',
                        'body' => 'My primary stack for APIs, domain logic, and native Windows tools.',
                        'icon' => 'dotnet',
                        'fallback' => '.N',
                        'color' => '#8b5cf6',
                        'tools' => ['.NET 10 / C#', 'ASP.NET Core', 'EF Core', 'WinUI 3'],
                    ],
                    [
                        'title' => 'Laravel',
                        'body' => 'Websites and client systems with clear server-side structure and static builds where they fit.',
                        'icon' => 'laravel',
                        'fallback' => 'L',
                        'color' => '#ff2d20',
                        'tools' => ['Laravel 13', 'Blade', 'PHPUnit / Pest', 'Vite'],
                    ],
                    [
                        'title' => 'Interfaces',
                        'body' => 'Angular product views, Blade pages, and native UI with focused interaction.',
                        'icon' => 'angular',
                        'fallback' => 'A',
                        'color' => '#dd0031',
                        'tools' => ['Angular', 'TypeScript', 'Tailwind CSS', 'MVVM'],
                    ],
                    [
                        'title' => 'Data & hosting',
                        'body' => 'From PostgreSQL and Google integrations to tested builds and Plesk in production.',
                        'icon' => 'postgresql',
                        'fallback' => 'PG',
                        'color' => '#4169e1',
                        'tools' => ['PostgreSQL', 'Google APIs', 'GitHub Actions', 'Herd / Plesk'],
                    ],
                ],
                'career_heading' => 'Career path',
                'career_label' => 'Experience',
                'career' => [
                    [
                        'period' => 'Aug 2019 — Aug 2023',
                        'title' => 'Application Developer EFZ',
                        'body' => 'Four-year apprenticeship at EcoLogic AG in Zurich.',
                    ],
                    [
                        'period' => 'Aug 2023 — Aug 2024',
                        'title' => 'Vocational baccalaureate (BMS)',
                        'body' => 'Vocational baccalaureate focused on economics.',
                    ],
                    [
                        'period' => 'Since Aug 2024',
                        'title' => 'Software Developer',
                        'body' => 'Full-stack software, independent products, and client systems.',
                    ],
                    [
                        'period' => 'Sep 2026 — Sep 2030',
                        'title' => 'Business Informatics BSc',
                        'body' => 'Studies at OST, starting in September 2026.',
                    ],
                ],
            ],
            'projects_page' => [
                'eyebrow' => 'Selected work',
                'featured_label' => 'Featured build',
                'secondary_label' => 'Additional work',
                'heading' => 'Projects',
                'intro' => 'Three current projects across product engineering, independent business, and native desktop software.',
                'items' => [
                    [
                        'slug' => 'quantified',
                        'name' => 'Quantified',
                        'type' => 'Personal analytics product',
                        'description' => 'A personal analytics platform that brings calendar, finance, coding, and local system data into dashboards and timelines.',
                        'tags' => ['Angular', '.NET / C#', 'PostgreSQL'],
                        'detail_route' => 'quantified',
                        'transition_theme' => 'quantified',
                    ],
                    [
                        'slug' => 'jay-jay',
                        'name' => 'Jay-Jay',
                        'type' => 'Digital service business',
                        'description' => 'My business for websites, hosting, and ongoing support, backed by jay-jay.ch and a separate Client Hub in development.',
                        'tags' => ['Business', 'Laravel 13', 'Product design'],
                        'detail_route' => 'jay-jay',
                        'transition_theme' => 'jay-jay',
                    ],
                    [
                        'slug' => 'sessiondeck',
                        'name' => 'SessionDeck',
                        'type' => 'Native workspace launcher',
                        'description' => 'An open-source Windows app that saves apps, commands, URLs, and folders as reusable profiles, then starts them in order.',
                        'tags' => ['WinUI 3', '.NET 10', 'MVVM'],
                        'detail_route' => 'session-deck',
                        'transition_theme' => 'session-deck',
                    ],
                ],
            ],
            'quantified_page' => [
                'slug' => 'quantified',
                'meta_description' => 'Quantified is Jeremy Läderach\'s full-stack personal analytics platform built with Angular, ASP.NET Core, PostgreSQL, and Google Calendar.',
                'back' => 'All projects',
                'eyebrow' => 'Product · Active build',
                'heading' => 'Quantified',
                'intro' => 'Quantified brings calendar, finance, coding, and local system data into dashboards and timelines. Long term, I want one place where I can see how different parts of my life change over time.',
                'status_label' => 'Status',
                'status' => 'Active work in progress',
                'role_label' => 'Role',
                'role' => 'Product design and full-stack engineering',
                'preview_label' => 'Quantified analytics workspace',
                'media' => [
                    [
                        'type' => 'quantified-workspace',
                        'view' => 'home',
                        'label' => 'Home workspace',
                        'description' => 'Calendar, finance, coding, and system data in one visual overview.',
                    ],
                    [
                        'type' => 'quantified-workspace',
                        'view' => 'calendar',
                        'label' => 'QCalendar',
                        'description' => 'Tracker events shown as timelines and category-based dashboards.',
                    ],
                    [
                        'type' => 'quantified-workspace',
                        'view' => 'finances',
                        'label' => 'QFinances',
                        'description' => 'Accounts and transactions shown in a focused local finance view.',
                    ],
                ],
                'product' => [
                    'label' => 'Product',
                    'heading' => 'All my data, made visible.',
                    'body' => 'The product starts with data I already collect: calendar events, finances, repository activity, and local system information. New modules can follow the same pattern, so the workspace can grow without becoming a set of disconnected apps.',
                    'notes' => [
                        ['label' => 'Current inputs', 'value' => 'Google Calendar, PostgreSQL, Git repositories, and local system checks.'],
                        ['label' => 'Views', 'value' => 'Calendar, finance, coding, and system views keep the details separate; Home summarizes them.'],
                        ['label' => 'Next step', 'value' => 'Add more data sources, then compare them over longer periods.'],
                    ],
                ],
                'stack' => [
                    'label' => 'Stack',
                    'heading' => 'Angular + .NET.',
                    'intro' => 'Angular handles the interface, ASP.NET Core the API and calculations. PostgreSQL stores finance data, and Google Calendar provides calendar events.',
                    'groups' => [
                        [
                            'title' => 'Frontend',
                            'body' => 'Angular feature areas and shared chart components turn API data into dashboards and timelines.',
                            'icon' => 'angular',
                            'fallback' => 'NG',
                            'color' => '#dd0031',
                            'tools' => ['Angular 22', 'TypeScript 6', 'RxJS', 'Chart.js'],
                        ],
                        [
                            'title' => 'Backend',
                            'body' => 'ASP.NET Core handles authentication, calendar parsing, analytics, and user-scoped finance endpoints.',
                            'icon' => 'dotnet',
                            'fallback' => '.N',
                            'color' => '#8b5cf6',
                            'tools' => ['.NET 10', 'C#', 'ASP.NET Core', 'Identity'],
                        ],
                        [
                            'title' => 'Data & integrations',
                            'body' => 'PostgreSQL stores QFinances data; Google Calendar supplies the first tracking input.',
                            'icon' => 'postgresql',
                            'fallback' => 'PG',
                            'color' => '#336791',
                            'tools' => ['PostgreSQL', 'EF Core', 'Calendar API', 'OAuth'],
                        ],
                    ],
                ],
            ],
            'jay_jay_page' => [
                'slug' => 'jay-jay',
                'meta_description' => 'Jay-Jay is Jeremy Läderach\'s digital service business, supported by a bilingual Laravel website and an evolving customer portal.',
                'back' => 'All projects',
                'eyebrow' => 'Business · Live',
                'heading' => 'Jay-Jay',
                'intro' => 'Jay-Jay is my business for websites, hosting, domains, email, and ongoing technical support. jay-jay.ch is live; the separate Client Hub is still in development.',
                'status_label' => 'Status',
                'status' => 'Operating · Client Hub in development',
                'role_label' => 'Role',
                'role' => 'Founder, product designer, and developer',
                'preview_label' => 'Jay-Jay website and Client Hub',
                'media' => [
                    [
                        'type' => 'jay-jay-web',
                        'label' => 'jay-jay.ch',
                        'description' => 'Services, hosting, and contact on the bilingual company website.',
                    ],
                    [
                        'type' => 'jay-jay-hub',
                        'view' => 'overview',
                        'label' => 'Customer overview',
                        'description' => 'Boards, private documents, invoices, and requests for one demo customer.',
                    ],
                    [
                        'type' => 'jay-jay-hub',
                        'view' => 'board',
                        'label' => 'Work board',
                        'description' => 'Website tickets organized by status from backlog to done.',
                    ],
                ],
                'preview' => [
                    'hub' => [
                        'badge' => 'Development build',
                        'navigation' => [
                            'overview' => 'Overview',
                            'board' => 'Boards',
                            'documents' => 'Documents',
                            'invoices' => 'Invoices',
                        ],
                        'eyebrow' => 'Client area',
                        'heading' => 'Welcome, Anna.',
                        'body' => 'Active work, private documents, and requests in one place.',
                        'customer' => ['initials' => 'AE', 'name' => 'Anna Example', 'company' => 'Demo Company'],
                        'cards' => [
                            ['label' => 'Active boards', 'value' => '02', 'meta' => 'Work and status in one place'],
                            ['label' => 'Private documents', 'value' => '03', 'meta' => 'Stored per customer'],
                            ['label' => 'Open requests', 'value' => '02', 'meta' => 'Direct replies in context'],
                        ],
                        'board' => [
                            'reference' => 'BOARD · WEBSITE & HOSTING',
                            'status' => 'In progress',
                            'heading' => 'Website relaunch',
                            'body' => 'One board for the customer’s active website work.',
                            'columns' => [
                                ['label' => 'Backlog', 'state' => '03 tickets'],
                                ['label' => 'In progress', 'state' => '02 tickets', 'current' => true],
                                ['label' => 'Done', 'state' => '08 tickets'],
                            ],
                            'ticket_label' => 'Current ticket',
                            'ticket' => 'Review staging content',
                        ],
                    ],
                ],
                'product' => [
                    'label' => 'Product',
                    'heading' => 'A small service business with its own software.',
                    'body' => 'Jay-Jay provides websites, hosting, domains, email, and direct technical support for small Swiss organizations. jay-jay.ch presents the offer and handles contact requests; the Client Hub is being built for boards, tickets, private documents, invoices, and requests.',
                    'notes' => [
                        ['label' => 'jay-jay.ch', 'value' => 'A bilingual Laravel source app exported as a static production build for Plesk.'],
                        ['label' => 'Client Hub', 'value' => 'Boards, tickets, replies, documents, invoices, requests, and company details.'],
                        ['label' => 'Demo status', 'value' => 'The Hub currently uses demo data and is not ready for real customer information.'],
                    ],
                ],
                'stack' => [
                    'label' => 'Stack',
                    'heading' => 'Two Laravel apps.',
                    'intro' => 'Jay-Jay Web is exported as a static site for Plesk. The Client Hub runs separately with a database and login because private customer data does not belong in the same static build.',
                    'groups' => [
                        [
                            'title' => 'Jay-Jay Web',
                            'body' => 'Laravel and Blade keep the bilingual source maintainable; jay-jay.ch runs the static export and standalone contact endpoint.',
                            'icon' => 'laravel',
                            'fallback' => 'LA',
                            'color' => '#ff2d20',
                            'tools' => ['Laravel 13', 'Blade', 'Tailwind CSS 4', 'Static export'],
                        ],
                        [
                            'title' => 'Client Hub',
                            'body' => 'The database-backed app separates customer and admin access across boards, tickets, documents, and invoices.',
                            'icon' => 'sqlite',
                            'fallback' => 'DB',
                            'color' => '#60a5fa',
                            'tools' => ['Fortify', 'Eloquent', 'SQLite', 'Private storage'],
                        ],
                        [
                            'title' => 'Checks & deployment',
                            'body' => 'Both repositories run formatting, static analysis, and feature tests; jay-jay.ch ships to Plesk as a generated build.',
                            'icon' => 'githubactions',
                            'fallback' => 'CI',
                            'color' => '#5f69e1',
                            'tools' => ['Pest 4', 'Larastan', 'GitHub Actions', 'Plesk'],
                        ],
                    ],
                ],
                'external_label' => 'Visit Jay-Jay',
                'external_url' => 'https://jay-jay.ch/en/',
            ],
            'sessiondeck_page' => [
                'slug' => 'sessiondeck',
                'preview_label' => 'SessionDeck profile editor with a reusable development workspace',
                'media' => [
                    [
                        'type' => 'sessiondeck-overview',
                        'label' => 'Profile catalog',
                        'description' => 'Saved Windows setups, ready to review and start.',
                    ],
                    [
                        'type' => 'sessiondeck-editor',
                        'label' => 'Profile editor',
                        'description' => 'Applications, commands, URLs, and folders in the order they will launch.',
                    ],
                    [
                        'type' => 'sessiondeck-result',
                        'label' => 'Session result',
                        'description' => 'A separate result for every item that started, was skipped, or failed.',
                    ],
                ],
                'meta_description' => 'SessionDeck is an open-source WinUI 3 workspace launcher for reusable Windows session profiles.',
                'back' => 'All projects',
                'eyebrow' => 'Desktop app · Open source',
                'heading' => 'SessionDeck',
                'intro' => 'A native Windows tool that saves applications, commands, URLs, and folders as reusable profiles, then starts them in order.',
                'status_label' => 'Status',
                'status' => 'Functional source-build MVP',
                'role_label' => 'Role',
                'role' => 'Product design and Windows engineering',
                'product' => [
                    'label' => 'Product',
                    'heading' => 'Save the setup. Start it as one session.',
                    'body' => 'A profile keeps applications, commands, URLs, and folders in a clear launch order. Before a run, SessionDeck checks paths, dependencies, and local ports, then starts the available items without claiming processes it did not launch.',
                    'notes' => [
                        ['label' => 'Explicit start', 'value' => 'Nothing launches until the user selects Start.'],
                        ['label' => 'Local by design', 'value' => 'No account, cloud service, telemetry, or administrator access is required.'],
                        ['label' => 'Safe ownership', 'value' => 'Only directly tracked processes from the current in-memory run can be stopped.'],
                    ],
                ],
                'stack' => [
                    'label' => 'Stack',
                    'heading' => 'WinUI 3 + .NET.',
                    'intro' => 'The WinUI app stays thin. Domain rules live in SessionDeck.Core, while Windows-specific persistence and process handling stay in a separate infrastructure project.',
                    'groups' => [
                        [
                            'title' => 'Native UI',
                            'body' => 'WinUI controls keep the desktop interface native without moving domain rules into view code.',
                            'icon' => 'winui',
                            'fallback' => 'UI',
                            'color' => '#3b82f6',
                            'tools' => ['WinUI 3', 'Windows App SDK 2.2', 'XAML', 'MVVM'],
                        ],
                        [
                            'title' => 'Core & tests',
                            'body' => 'Domain models, validation, orchestration, and xUnit tests stay independent of WinUI.',
                            'icon' => 'dotnet',
                            'fallback' => '.N',
                            'color' => '#8b5cf6',
                            'tools' => ['.NET 10', 'C#', 'xUnit', 'Dependency injection'],
                        ],
                        [
                            'title' => 'Windows runtime',
                            'body' => 'JSON persistence, readiness checks, Terminal integration, and process APIs stay in the Windows infrastructure layer.',
                            'icon' => 'json',
                            'fallback' => '{}',
                            'color' => '#f59e0b',
                            'tools' => ['JSON', 'Windows Terminal', 'Readiness checks', 'Process APIs'],
                        ],
                    ],
                ],
                'external_label' => 'View the GitHub repository',
                'external_url' => 'https://github.com/jeremylaederach/session-deck',
            ],
            'contact_page' => [
                'eyebrow' => 'Start a conversation',
                'heading' => 'Contact',
                'intro' => 'Email is the best first step. Send the rough goal, links, constraints, and what a good outcome should feel like.',
                'direct_label' => 'Write directly',
                'direct_heading' => 'Tell me what you want to build.',
                'context_label' => 'A useful first note',
                'context' => 'A short outline of the goal, timing, and relevant links is enough. I will reply with the next useful steps.',
                'channels_label' => 'Elsewhere',
            ],
            'not_found' => [
                'eyebrow' => 'Lost route',
                'heading' => 'Page not found',
                'intro' => 'The address does not lead anywhere, but the rest of the portfolio is right where it should be.',
                'action' => 'Back to home',
            ],
            'imprint' => [
                'eyebrow' => 'Legal',
                'title' => 'Legal notice',
                'intro' => 'Ownership and contact details for this personal portfolio.',
                'sections' => [
                    [
                        'title' => 'Site operator',
                        'body' => ['Jeremy Läderach operates this personal portfolio from Switzerland and is responsible for its editorial content.'],
                    ],
                    [
                        'title' => 'Contact',
                        'body' => ['For questions about this website or its content, use the email address below.'],
                        'links' => [['label' => 'info@jeremylaederach.ch', 'url' => 'mailto:info@jeremylaederach.ch']],
                    ],
                    [
                        'title' => 'Content and copyright',
                        'body' => ['Unless stated otherwise, the text, code, visual identity, and original presentation on this website belong to Jeremy Läderach. Product names, trademarks, and third-party materials remain the property of their respective owners.'],
                    ],
                    [
                        'title' => 'External links',
                        'body' => ['Links to external websites are reviewed when published. Their operators remain responsible for their content and data-processing practices.'],
                    ],
                ],
            ],
            'privacy' => [
                'eyebrow' => 'Privacy',
                'title' => 'Privacy notice',
                'intro' => 'A concise account of the limited data this portfolio processes and why.',
                'updated' => 'Last updated: July 16, 2026',
                'sections' => [
                    [
                        'title' => 'Who is responsible',
                        'body' => ['Jeremy Läderach, Switzerland, is responsible for data processing connected with this website.'],
                        'links' => [['label' => 'info@jeremylaederach.ch', 'url' => 'mailto:info@jeremylaederach.ch']],
                    ],
                    [
                        'title' => 'Technical access data',
                        'body' => [
                            'When this website is requested, the hosting infrastructure may process technical data such as the IP address, timestamp, requested page, browser information, and referring address.',
                            'This data is used only to deliver, secure, and troubleshoot the website. It is retained only for as long as operational and security purposes require.',
                        ],
                    ],
                    [
                        'title' => 'Local preference',
                        'body' => [
                            'The sound control stores one mute preference in your browser\'s local storage. It remains on your device and is not used to identify or track you.',
                            'The deployed portfolio is a static website and does not set application, analytics, advertising, or marketing cookies. It also does not use trackers or externally hosted fonts.',
                        ],
                    ],
                    [
                        'title' => 'Contact and external services',
                        'body' => [
                            'If you contact me by email, I process the information you provide to answer your message and continue the conversation. It is kept only while needed for that purpose or applicable obligations.',
                            'GitHub and LinkedIn receive data only when you choose to follow an external link. Their own privacy terms then apply, and processing may take place outside Switzerland.',
                        ],
                    ],
                    [
                        'title' => 'Your rights',
                        'body' => ['Subject to applicable Swiss data-protection law, you may request information, correction, deletion, restriction, or the release of your personal data. Contact me by email to exercise these rights.'],
                        'links' => [['label' => 'Federal Data Protection and Information Commissioner', 'url' => 'https://www.edoeb.admin.ch/en']],
                    ],
                ],
            ],
        ],

        'de' => [
            'meta' => [
                'title' => 'Jeremy Läderach',
                'description' => 'Persönliches Portfolio von Jeremy Läderach, einem Softwareentwickler mit Fokus auf praktische Websysteme mit Laravel, .NET und Angular.',
            ],
            'ui' => [
                'skip' => 'Zum Inhalt springen',
                'language' => 'Sprache',
                'menu' => 'Hauptnavigation',
                'brand' => 'Jeremy Läderach Startseite',
                'role' => 'Softwareentwickler',
                'open' => 'Öffnen',
                'footer_navigation' => 'Entdecken',
                'legal_navigation' => 'Rechtliches und externe Links',
                'back_to_top' => 'Nach oben',
                'sound_mute' => 'Interface-Töne ausschalten',
                'sound_enable' => 'Interface-Töne einschalten',
                'project_media' => 'Projektansichten',
                'carousel' => 'Karussell',
                'media_previous' => 'Vorherige Ansicht',
                'media_next' => 'Nächste Ansicht',
                'media_view' => 'Ansicht',
                'next_project' => 'Nächstes Projekt',
            ],
            'nav' => [
                ['label' => 'Start', 'route' => 'home', 'icon' => 'home'],
                ['label' => 'Projekte', 'route' => 'projects', 'icon' => 'folder'],
                ['label' => 'Profil', 'route' => 'about', 'icon' => 'user'],
                ['label' => 'Kontakt', 'route' => 'contact', 'icon' => 'mail'],
            ],
            'home' => [
                'statement' => 'Ich entwickle',
                'statement_accent' => 'nützliche digitale Systeme.',
                'summary' => 'Ich konzipiere und entwickle Software, die komplexe Ideen einfach macht.',
                'explore' => 'Projekte entdecken',
                'index_label' => 'Start',
                'routes' => [
                    [
                        'label' => 'Projekte',
                        'description' => 'Produkte, Migrationen und Kundenprojekte.',
                        'route' => 'projects',
                    ],
                    [
                        'label' => 'Über mich',
                        'description' => 'Hintergrund, Erfahrung und die Technologien hinter meiner Arbeit.',
                        'route' => 'about',
                    ],
                    [
                        'label' => 'Kontakt',
                        'description' => 'Der direkte Weg für eine fokussierte Zusammenarbeit.',
                        'route' => 'contact',
                    ],
                ],
            ],
            'about_page' => [
                'eyebrow' => 'Profil',
                'heading' => 'Über mich',
                'intro' => 'Ich bin Jeremy, Softwareentwickler aus Zürich. Ich entwickle Produkte über den ganzen Stack – vom C#-Backend über das Interface bis zum Deployment.',
                'story_link' => 'Kurzprofil',
                'story_heading' => 'Kurzprofil.',
                'story_current' => 'Aktuell entwickle ich Full-Stack-Software und eigene Produkte: Quantified mit Angular, ASP.NET Core und PostgreSQL, SessionDeck als native .NET-App und die Laravel-Systeme hinter Jay-Jay.',
                'story_notes' => [
                    [
                        'label' => 'Grundlage',
                        'value' => 'Meine Grundlage ist die vierjährige EFZ-Lehre als Applikationsentwickler bei EcoLogic AG. Dort habe ich gelernt, Anforderungen in Software zu übersetzen, die im Alltag verständlich und wartbar bleibt.',
                    ],
                    [
                        'label' => 'Ab September 2026',
                        'value' => 'Ich starte den BSc Wirtschaftsinformatik an der OST – als nächsten Schritt zwischen Software, Produkt und Business.',
                    ],
                ],
                'playground_label' => 'Code',
                'playground_heading' => 'Playground.',
                'playground_intro' => 'Drei kleine Demos in purem JavaScript. Input ändern und direkt sehen, was im Hintergrund passiert.',
                'playground' => [
                    'sorting' => [
                        'title' => 'Sorting',
                        'run' => 'Starten',
                        'shuffle' => 'Mischen',
                        'metric' => 'Vergleiche',
                        'complete' => 'Sortiert',
                        'algorithms' => [
                            'quick' => [
                                'label' => 'Quick',
                                'description' => 'Wählt einen Pivot und schiebt kleinere Werte nach links, grössere nach rechts. Diese Aufteilung wiederholt sich, bis jede Gruppe sortiert ist.',
                            ],
                            'merge' => [
                                'label' => 'Merge',
                                'description' => 'Teilt die Liste immer weiter und fügt die Teile sortiert zusammen. Dabei entsteht Schritt für Schritt wieder eine geordnete Liste.',
                            ],
                            'insertion' => [
                                'label' => 'Insertion',
                                'description' => 'Nimmt einen Wert und schiebt ihn an die richtige Stelle im bereits sortierten Teil. So wächst der geordnete Bereich Balken für Balken.',
                            ],
                            'selection' => [
                                'label' => 'Selection',
                                'description' => 'Sucht jeweils den kleinsten übrigen Wert und setzt ihn nach vorne. Nach jedem Durchlauf steht ein weiterer Balken endgültig richtig.',
                            ],
                            'bubble' => [
                                'label' => 'Bubble',
                                'description' => 'Vergleicht Nachbarn und tauscht sie, wenn sie falsch stehen. Ein Durchlauf ohne Tausch bedeutet, dass die Liste fertig sortiert ist.',
                            ],
                        ],
                    ],
                    'network' => [
                        'title' => 'Neural Network',
                        'description' => 'Zeichne eine 0, 1 oder 2. Jedes Feld wird zur Zahl; drei Ausgänge vergleichen das Muster, der stärkste gewinnt.',
                        'run' => 'Erkennen',
                        'reset' => 'Leeren',
                        'metric' => 'Erkannt',
                        'empty' => 'Zuerst eine Zahl zeichnen',
                        'default' => '2',
                        'keyboard_note' => 'Mit den Pfeiltasten durch die Pixel navigieren. Mit Leertaste oder Enter ein Feld ein- oder ausschalten.',
                        'visual' => [
                            'input' => 'Pixel',
                            'output' => 'Ergebnis',
                            'pixel' => 'Pixel',
                            'on' => 'an',
                            'off' => 'aus',
                        ],
                        'presets' => [
                            '0' => ['label' => '0'],
                            '1' => ['label' => '1'],
                            '2' => ['label' => '2'],
                        ],
                    ],
                    'pathfinding' => [
                        'title' => 'Pathfinder',
                        'description' => 'Wände bearbeiten, Suchart wählen und die Wege vergleichen.',
                        'strategies' => [
                            'shortest' => [
                                'label' => 'Kürzester Weg',
                                'description' => 'Prüft von A aus Feld für Feld und garantiert die wenigsten Schritte.',
                            ],
                            'guided' => [
                                'label' => 'Weniger prüfen',
                                'description' => 'Nutzt die Distanz zu B, prüft meist weniger Felder und findet trotzdem einen kürzesten Weg.',
                            ],
                            'straight' => [
                                'label' => 'Weniger Kurven',
                                'description' => 'Bevorzugt einen geraderen Weg, auch wenn er ein paar Schritte länger wird.',
                            ],
                        ],
                        'keyboard_note' => 'Mit den Pfeiltasten durch das Raster navigieren. Mit Leertaste oder Enter ein Feld sperren oder öffnen.',
                        'run' => 'Weg finden',
                        'reset' => 'Zurücksetzen',
                        'metric' => 'Geprüft · Schritte · Kurven',
                        'no_path' => 'Kein freier Weg',
                        'visual' => [
                            'checked' => 'geprüft',
                            'steps' => 'Schritte',
                            'turns' => 'Kurven',
                            'cell' => 'Feld',
                            'blocked' => 'gesperrt',
                            'open' => 'offen',
                            'start' => 'Start',
                            'goal' => 'Ziel',
                            'fixed' => 'kann nicht gesperrt werden',
                        ],
                    ],
                ],
                'technology_heading' => 'Stack',
                'technology_label' => 'Tools',
                'technology_intro' => 'Der Stack, mit dem ich tatsächlich arbeite – nicht jede Technologie, die ich einmal ausprobiert habe.',
                'technology_groups' => [
                    [
                        'title' => '.NET & C#',
                        'body' => 'Mein Haupt-Stack für APIs, Domänenlogik und native Windows-Tools.',
                        'icon' => 'dotnet',
                        'fallback' => '.N',
                        'color' => '#8b5cf6',
                        'tools' => ['.NET 10 / C#', 'ASP.NET Core', 'EF Core', 'WinUI 3'],
                    ],
                    [
                        'title' => 'Laravel',
                        'body' => 'Websites und Kundensysteme mit klarer Serverstruktur und statischen Builds, wo sie sinnvoll sind.',
                        'icon' => 'laravel',
                        'fallback' => 'L',
                        'color' => '#ff2d20',
                        'tools' => ['Laravel 13', 'Blade', 'PHPUnit / Pest', 'Vite'],
                    ],
                    [
                        'title' => 'Interfaces',
                        'body' => 'Angular-Produktoberflächen, Blade-Seiten und native UI mit fokussierter Interaktion.',
                        'icon' => 'angular',
                        'fallback' => 'A',
                        'color' => '#dd0031',
                        'tools' => ['Angular', 'TypeScript', 'Tailwind CSS', 'MVVM'],
                    ],
                    [
                        'title' => 'Daten & Hosting',
                        'body' => 'Von PostgreSQL und Google-Integrationen bis zu getesteten Builds und Plesk in Produktion.',
                        'icon' => 'postgresql',
                        'fallback' => 'PG',
                        'color' => '#4169e1',
                        'tools' => ['PostgreSQL', 'Google APIs', 'GitHub Actions', 'Herd / Plesk'],
                    ],
                ],
                'career_heading' => 'Werdegang',
                'career_label' => 'Erfahrung',
                'career' => [
                    [
                        'period' => 'Aug. 2019 — Aug. 2023',
                        'title' => 'Applikationsentwickler EFZ',
                        'body' => 'Vierjährige Lehre bei EcoLogic AG in Zürich.',
                    ],
                    [
                        'period' => 'Aug. 2023 — Aug. 2024',
                        'title' => 'Berufsmaturität (BMS)',
                        'body' => 'Berufsmaturität mit Schwerpunkt Wirtschaft.',
                    ],
                    [
                        'period' => 'Seit Aug. 2024',
                        'title' => 'Softwareentwickler',
                        'body' => 'Full-Stack-Software, eigene Produkte und Kundensysteme.',
                    ],
                    [
                        'period' => 'Sep. 2026 — Sep. 2030',
                        'title' => 'BSc Wirtschaftsinformatik',
                        'body' => 'Studium an der OST ab September 2026.',
                    ],
                ],
            ],
            'projects_page' => [
                'eyebrow' => 'Ausgewählte Arbeiten',
                'featured_label' => 'Hauptprojekt',
                'secondary_label' => 'Weitere Arbeiten',
                'heading' => 'Projekte',
                'intro' => 'Drei aktuelle Projekte aus Produktentwicklung, eigenem Unternehmen und nativer Desktop-Software.',
                'items' => [
                    [
                        'slug' => 'quantified',
                        'name' => 'Quantified',
                        'type' => 'Persönliches Analyseprodukt',
                        'description' => 'Eine persönliche Analytics-Plattform für Kalender-, Finanz-, Coding- und lokale Systemdaten – aufbereitet als Dashboards und Timelines.',
                        'tags' => ['Angular', '.NET / C#', 'PostgreSQL'],
                        'detail_route' => 'quantified',
                        'transition_theme' => 'quantified',
                    ],
                    [
                        'slug' => 'jay-jay',
                        'name' => 'Jay-Jay',
                        'type' => 'Digitales Dienstleistungsunternehmen',
                        'description' => 'Mein Unternehmen für Websites, Hosting und laufende Betreuung – mit jay-jay.ch und einem separaten Client Hub in Entwicklung.',
                        'tags' => ['Unternehmen', 'Laravel 13', 'Product Design'],
                        'detail_route' => 'jay-jay',
                        'transition_theme' => 'jay-jay',
                    ],
                    [
                        'slug' => 'sessiondeck',
                        'name' => 'SessionDeck',
                        'type' => 'Nativer Workspace-Launcher',
                        'description' => 'Eine Open-Source-Windows-App, die Apps, Commands, URLs und Ordner als wiederverwendbare Profile speichert und der Reihe nach startet.',
                        'tags' => ['WinUI 3', '.NET 10', 'MVVM'],
                        'detail_route' => 'session-deck',
                        'transition_theme' => 'session-deck',
                    ],
                ],
            ],
            'quantified_page' => [
                'slug' => 'quantified',
                'meta_description' => 'Quantified ist Jeremy Läderachs persönliche Full-Stack-Analytics-Plattform mit Angular, ASP.NET Core, PostgreSQL und Google Calendar.',
                'back' => 'Alle Projekte',
                'eyebrow' => 'Produkt · In Entwicklung',
                'heading' => 'Quantified',
                'intro' => 'Quantified bringt Kalender-, Finanz-, Coding- und lokale Systemdaten in Dashboards und Timelines zusammen. Langfristig möchte ich an einem Ort sehen, wie sich verschiedene Bereiche meines Lebens entwickeln.',
                'status_label' => 'Status',
                'status' => 'Aktiv in Entwicklung',
                'role_label' => 'Rolle',
                'role' => 'Product Design und Full-Stack-Entwicklung',
                'preview_label' => 'Quantified Analytics Workspace',
                'media' => [
                    [
                        'type' => 'quantified-workspace',
                        'view' => 'home',
                        'label' => 'Home-Workspace',
                        'description' => 'Kalender-, Finanz-, Coding- und Systemdaten in einer visuellen Übersicht.',
                    ],
                    [
                        'type' => 'quantified-workspace',
                        'view' => 'calendar',
                        'label' => 'QCalendar',
                        'description' => 'Tracker-Events als Timelines und kategoriebasierte Dashboards.',
                    ],
                    [
                        'type' => 'quantified-workspace',
                        'view' => 'finances',
                        'label' => 'QFinances',
                        'description' => 'Konten und Transaktionen in einer fokussierten lokalen Finanzansicht.',
                    ],
                ],
                'product' => [
                    'label' => 'Produkt',
                    'heading' => 'Alle meine Daten, sichtbar gemacht.',
                    'body' => 'Die Grundlage sind Daten, die bereits anfallen: Kalender-Events, Finanzen, Repository-Aktivität und lokale Systeminformationen. Weitere Module können demselben Muster folgen, ohne dass daraus wieder einzelne, getrennte Apps werden.',
                    'notes' => [
                        ['label' => 'Aktuelle Quellen', 'value' => 'Google Calendar, PostgreSQL, Git-Repositories und lokale System-Checks.'],
                        ['label' => 'Ansichten', 'value' => 'Kalender, Finanzen, Coding und System bleiben getrennt; Home fasst sie zusammen.'],
                        ['label' => 'Nächster Schritt', 'value' => 'Weitere Datenquellen anbinden und Entwicklungen über längere Zeit vergleichen.'],
                    ],
                ],
                'stack' => [
                    'label' => 'Stack',
                    'heading' => 'Angular + .NET.',
                    'intro' => 'Angular übernimmt die Oberfläche, ASP.NET Core die API und Berechnungen. PostgreSQL speichert Finanzdaten; Google Calendar liefert die Kalender-Events.',
                    'groups' => [
                        [
                            'title' => 'Frontend',
                            'body' => 'Angular-Features und gemeinsame Chart-Komponenten machen aus API-Daten Dashboards und Timelines.',
                            'icon' => 'angular',
                            'fallback' => 'NG',
                            'color' => '#dd0031',
                            'tools' => ['Angular 22', 'TypeScript 6', 'RxJS', 'Chart.js'],
                        ],
                        [
                            'title' => 'Backend',
                            'body' => 'ASP.NET Core übernimmt Authentifizierung, Kalender-Parsing, Analytics und benutzerbezogene Finanz-Endpunkte.',
                            'icon' => 'dotnet',
                            'fallback' => '.N',
                            'color' => '#8b5cf6',
                            'tools' => ['.NET 10', 'C#', 'ASP.NET Core', 'Identity'],
                        ],
                        [
                            'title' => 'Daten & Integrationen',
                            'body' => 'PostgreSQL speichert die QFinances-Daten; Google Calendar liefert die ersten Tracking-Daten.',
                            'icon' => 'postgresql',
                            'fallback' => 'PG',
                            'color' => '#336791',
                            'tools' => ['PostgreSQL', 'EF Core', 'Calendar API', 'OAuth'],
                        ],
                    ],
                ],
            ],
            'jay_jay_page' => [
                'slug' => 'jay-jay',
                'meta_description' => 'Jay-Jay ist Jeremy Läderachs digitales Dienstleistungsunternehmen mit einer zweisprachigen Laravel-Website und einem wachsenden Kundenportal.',
                'back' => 'Alle Projekte',
                'eyebrow' => 'Unternehmen · Live',
                'heading' => 'Jay-Jay',
                'intro' => 'Jay-Jay ist mein Unternehmen für Websites, Hosting, Domains, E-Mail und laufende technische Betreuung. jay-jay.ch ist live; der separate Client Hub befindet sich noch in Entwicklung.',
                'status_label' => 'Status',
                'status' => 'Aktiv · Client Hub in Entwicklung',
                'role_label' => 'Rolle',
                'role' => 'Gründer, Product Designer und Entwickler',
                'preview_label' => 'Jay-Jay Website und Client Hub',
                'media' => [
                    [
                        'type' => 'jay-jay-web',
                        'label' => 'jay-jay.ch',
                        'description' => 'Leistungen, Hosting und Kontakt auf der zweisprachigen Unternehmenswebsite.',
                    ],
                    [
                        'type' => 'jay-jay-hub',
                        'view' => 'overview',
                        'label' => 'Kundenübersicht',
                        'description' => 'Boards, private Dokumente, Rechnungen und Anfragen für einen Demo-Kunden.',
                    ],
                    [
                        'type' => 'jay-jay-hub',
                        'view' => 'board',
                        'label' => 'Work Board',
                        'description' => 'Website-Tickets nach Bearbeitungsstand von Backlog bis Erledigt.',
                    ],
                ],
                'preview' => [
                    'hub' => [
                        'badge' => 'Development-Build',
                        'navigation' => [
                            'overview' => 'Übersicht',
                            'board' => 'Boards',
                            'documents' => 'Dokumente',
                            'invoices' => 'Rechnungen',
                        ],
                        'eyebrow' => 'Kundenbereich',
                        'heading' => 'Willkommen, Anna.',
                        'body' => 'Aktive Arbeit, private Dokumente und Anfragen an einem Ort.',
                        'customer' => ['initials' => 'AM', 'name' => 'Anna Muster', 'company' => 'Demo-Unternehmen'],
                        'cards' => [
                            ['label' => 'Aktive Boards', 'value' => '02', 'meta' => 'Arbeit und Status an einem Ort'],
                            ['label' => 'Private Dokumente', 'value' => '03', 'meta' => 'Pro Kunde gespeichert'],
                            ['label' => 'Offene Anfragen', 'value' => '02', 'meta' => 'Direkte Antworten im Kontext'],
                        ],
                        'board' => [
                            'reference' => 'BOARD · WEBSITE & HOSTING',
                            'status' => 'In Arbeit',
                            'heading' => 'Website-Relaunch',
                            'body' => 'Ein Board für die laufende Website-Arbeit des Kunden.',
                            'columns' => [
                                ['label' => 'Backlog', 'state' => '03 Tickets'],
                                ['label' => 'In Arbeit', 'state' => '02 Tickets', 'current' => true],
                                ['label' => 'Erledigt', 'state' => '08 Tickets'],
                            ],
                            'ticket_label' => 'Aktuelles Ticket',
                            'ticket' => 'Staging-Inhalte prüfen',
                        ],
                    ],
                ],
                'product' => [
                    'label' => 'Produkt',
                    'heading' => 'Ein kleines Dienstleistungsunternehmen mit eigener Software.',
                    'body' => 'Jay-Jay bietet Websites, Hosting, Domains, E-Mail und direkten technischen Support für kleine Schweizer Organisationen. jay-jay.ch stellt das Angebot vor und verarbeitet Kontaktanfragen; der Client Hub entsteht für Boards, Tickets, private Dokumente, Rechnungen und Anfragen.',
                    'notes' => [
                        ['label' => 'jay-jay.ch', 'value' => 'Eine zweisprachige Laravel-Anwendung als Quelle für den statischen Plesk-Build.'],
                        ['label' => 'Client Hub', 'value' => 'Boards, Tickets, Antworten, Dokumente, Rechnungen, Anfragen und Firmendaten.'],
                        ['label' => 'Demo-Betrieb', 'value' => 'Der Hub arbeitet aktuell mit Demo-Daten und ist noch nicht für echte Kundendaten bereit.'],
                    ],
                ],
                'stack' => [
                    'label' => 'Stack',
                    'heading' => 'Zwei Laravel-Apps.',
                    'intro' => 'Jay-Jay Web wird als statische Website für Plesk exportiert. Der Client Hub läuft separat mit Datenbank und Login, weil private Kundendaten nicht in denselben statischen Build gehören.',
                    'groups' => [
                        [
                            'title' => 'Jay-Jay Web',
                            'body' => 'Laravel und Blade halten die zweisprachige Quelle wartbar; auf jay-jay.ch laufen der statische Export und der separate Kontakt-Endpunkt.',
                            'icon' => 'laravel',
                            'fallback' => 'LA',
                            'color' => '#ff2d20',
                            'tools' => ['Laravel 13', 'Blade', 'Tailwind CSS 4', 'Statischer Export'],
                        ],
                        [
                            'title' => 'Client Hub',
                            'body' => 'Die datenbankgestützte Anwendung trennt Kunden- und Admin-Zugriffe auf Boards, Tickets, Dokumente und Rechnungen.',
                            'icon' => 'sqlite',
                            'fallback' => 'DB',
                            'color' => '#60a5fa',
                            'tools' => ['Fortify', 'Eloquent', 'SQLite', 'Private Storage'],
                        ],
                        [
                            'title' => 'Checks & Deployment',
                            'body' => 'Beide Repositories prüfen Formatierung, statische Analyse und Features; jay-jay.ch wird als generierter Build auf Plesk veröffentlicht.',
                            'icon' => 'githubactions',
                            'fallback' => 'CI',
                            'color' => '#5f69e1',
                            'tools' => ['Pest 4', 'Larastan', 'GitHub Actions', 'Plesk'],
                        ],
                    ],
                ],
                'external_label' => 'Jay-Jay besuchen',
                'external_url' => 'https://jay-jay.ch/de/',
            ],
            'sessiondeck_page' => [
                'slug' => 'sessiondeck',
                'preview_label' => 'SessionDeck Profileditor mit einem wiederverwendbaren Development Workspace',
                'media' => [
                    [
                        'type' => 'sessiondeck-overview',
                        'label' => 'Profilübersicht',
                        'description' => 'Gespeicherte Windows-Setups zum Prüfen und Starten.',
                    ],
                    [
                        'type' => 'sessiondeck-editor',
                        'label' => 'Profileditor',
                        'description' => 'Apps, Commands, URLs und Ordner in ihrer späteren Startreihenfolge.',
                    ],
                    [
                        'type' => 'sessiondeck-result',
                        'label' => 'Session-Ergebnis',
                        'description' => 'Ein eigenes Ergebnis für jedes gestartete, übersprungene oder fehlgeschlagene Element.',
                    ],
                ],
                'meta_description' => 'SessionDeck ist ein Open-Source-Workspace-Launcher mit WinUI 3 für wiederverwendbare Windows-Profile.',
                'back' => 'Alle Projekte',
                'eyebrow' => 'Desktop-App · Open Source',
                'heading' => 'SessionDeck',
                'intro' => 'Ein natives Windows-Tool, das Apps, Commands, URLs und Ordner als wiederverwendbare Profile speichert und der Reihe nach startet.',
                'status_label' => 'Status',
                'status' => 'Funktionaler Source-Build-MVP',
                'role_label' => 'Rolle',
                'role' => 'Product Design und Windows-Entwicklung',
                'product' => [
                    'label' => 'Produkt',
                    'heading' => 'Setup speichern. Als Session starten.',
                    'body' => 'Ein Profil hält Apps, Commands, URLs und Ordner in einer klaren Startreihenfolge. Vor jedem Lauf prüft SessionDeck Pfade, Abhängigkeiten und lokale Ports und startet danach die verfügbaren Einträge, ohne fremde Prozesse als eigene zu behandeln.',
                    'notes' => [
                        ['label' => 'Bewusster Start', 'value' => 'Nichts startet, bevor der Nutzer Start auswählt.'],
                        ['label' => 'Konsequent lokal', 'value' => 'Accounts, Cloud-Dienste, Telemetrie und Administratorrechte sind nicht nötig.'],
                        ['label' => 'Kontrollierte Prozesse', 'value' => 'Gestoppt werden können nur Prozesse, die im aktuellen Lauf direkt erfasst wurden.'],
                    ],
                ],
                'stack' => [
                    'label' => 'Stack',
                    'heading' => 'WinUI 3 + .NET.',
                    'intro' => 'Die WinUI-App bleibt schlank. Domänenlogik liegt in SessionDeck.Core; Windows-spezifische Persistenz und Prozesssteuerung liegen in einem eigenen Infrastrukturprojekt.',
                    'groups' => [
                        [
                            'title' => 'Native UI',
                            'body' => 'Die Desktop-App nutzt WinUI-Controls, ohne Domänenlogik in die Views zu verschieben.',
                            'icon' => 'winui',
                            'fallback' => 'UI',
                            'color' => '#3b82f6',
                            'tools' => ['WinUI 3', 'Windows App SDK 2.2', 'XAML', 'MVVM'],
                        ],
                        [
                            'title' => 'Core & Tests',
                            'body' => 'Domänenmodelle, Validierung, Orchestrierung und xUnit-Tests bleiben unabhängig von WinUI.',
                            'icon' => 'dotnet',
                            'fallback' => '.N',
                            'color' => '#8b5cf6',
                            'tools' => ['.NET 10', 'C#', 'xUnit', 'Dependency Injection'],
                        ],
                        [
                            'title' => 'Windows Runtime',
                            'body' => 'JSON-Persistenz, Readiness Checks, Terminal-Integration und Prozess-APIs liegen im Windows-Infrastruktur-Layer.',
                            'icon' => 'json',
                            'fallback' => '{}',
                            'color' => '#f59e0b',
                            'tools' => ['JSON', 'Windows Terminal', 'Readiness Checks', 'Process APIs'],
                        ],
                    ],
                ],
                'external_label' => 'GitHub-Repository ansehen',
                'external_url' => 'https://github.com/jeremylaederach/session-deck',
            ],
            'contact_page' => [
                'eyebrow' => 'Gespräch beginnen',
                'heading' => 'Kontakt',
                'intro' => 'E-Mail ist der beste erste Schritt. Schick mir dein Ziel, relevante Links und die wichtigsten Rahmenbedingungen.',
                'direct_label' => 'Direkt schreiben',
                'direct_heading' => 'Erzähl mir, was du umsetzen möchtest.',
                'context_label' => 'Für einen guten Start',
                'context' => 'Ein kurzer Überblick über Ziel, Zeitrahmen und relevante Links reicht. Ich melde mich mit den nächsten sinnvollen Schritten.',
                'channels_label' => 'Weitere Profile',
            ],
            'not_found' => [
                'eyebrow' => 'Falscher Weg',
                'heading' => 'Seite nicht gefunden',
                'intro' => 'Diese Adresse führt nirgendwohin. Der Rest des Portfolios ist aber genau dort, wo er sein soll.',
                'action' => 'Zurück zur Startseite',
            ],
            'imprint' => [
                'eyebrow' => 'Rechtliches',
                'title' => 'Impressum',
                'intro' => 'Angaben zur Verantwortung und Kontaktmöglichkeit für dieses persönliche Portfolio.',
                'sections' => [
                    [
                        'title' => 'Betreiber',
                        'body' => ['Jeremy Läderach betreibt dieses persönliche Portfolio aus der Schweiz und ist für die redaktionellen Inhalte verantwortlich.'],
                    ],
                    [
                        'title' => 'Kontakt',
                        'body' => ['Für Fragen zu dieser Website oder ihren Inhalten steht die folgende E-Mail-Adresse zur Verfügung.'],
                        'links' => [['label' => 'info@jeremylaederach.ch', 'url' => 'mailto:info@jeremylaederach.ch']],
                    ],
                    [
                        'title' => 'Inhalte und Urheberrecht',
                        'body' => ['Sofern nicht anders angegeben, stammen Texte, Code, visuelle Identität und die eigenständige Präsentation dieser Website von Jeremy Läderach. Produktnamen, Marken und Inhalte Dritter bleiben Eigentum ihrer jeweiligen Rechteinhaber.'],
                    ],
                    [
                        'title' => 'Externe Links',
                        'body' => ['Verlinkte externe Websites werden bei der Veröffentlichung geprüft. Für deren Inhalte und Datenbearbeitung bleiben die jeweiligen Betreiber verantwortlich.'],
                    ],
                ],
            ],
            'privacy' => [
                'eyebrow' => 'Datenschutz',
                'title' => 'Datenschutzerklärung',
                'intro' => 'Eine kompakte Übersicht darüber, welche wenigen Daten dieses Portfolio bearbeitet und weshalb.',
                'updated' => 'Stand: 16. Juli 2026',
                'sections' => [
                    [
                        'title' => 'Verantwortliche Person',
                        'body' => ['Jeremy Läderach, Schweiz, ist für die Datenbearbeitung im Zusammenhang mit dieser Website verantwortlich.'],
                        'links' => [['label' => 'info@jeremylaederach.ch', 'url' => 'mailto:info@jeremylaederach.ch']],
                    ],
                    [
                        'title' => 'Technische Zugriffsdaten',
                        'body' => [
                            'Beim Aufruf dieser Website kann die Hosting-Infrastruktur technische Daten wie IP-Adresse, Zeitpunkt, aufgerufene Seite, Browserinformationen und verweisende Adresse bearbeiten.',
                            'Diese Daten dienen ausschliesslich der Auslieferung, Sicherheit und Fehleranalyse. Sie werden nur so lange aufbewahrt, wie es für den Betrieb und die Sicherheit erforderlich ist.',
                        ],
                    ],
                    [
                        'title' => 'Lokale Einstellung',
                        'body' => [
                            'Die Tonsteuerung speichert eine einzige Stummschaltungs-Einstellung im lokalen Speicher deines Browsers. Sie bleibt auf deinem Gerät und dient weder der Identifikation noch dem Tracking.',
                            'Das veröffentlichte Portfolio ist eine statische Website und setzt keine Anwendungs-, Analyse-, Werbe- oder Marketing-Cookies. Es verwendet zudem keine Tracker oder extern eingebundenen Schriftarten.',
                        ],
                    ],
                    [
                        'title' => 'Kontakt und externe Dienste',
                        'body' => [
                            'Wenn du mich per E-Mail kontaktierst, bearbeite ich deine Angaben, um deine Nachricht zu beantworten und die Kommunikation fortzuführen. Die Daten bleiben nur so lange gespeichert, wie es dafür oder für geltende Pflichten erforderlich ist.',
                            'GitHub und LinkedIn erhalten erst Daten, wenn du einen externen Link aufrufst. Danach gelten die Datenschutzbestimmungen des jeweiligen Anbieters; eine Bearbeitung ausserhalb der Schweiz ist möglich.',
                        ],
                    ],
                    [
                        'title' => 'Deine Rechte',
                        'body' => ['Im Rahmen des anwendbaren Schweizer Datenschutzrechts kannst du Auskunft, Berichtigung, Löschung, Einschränkung oder Herausgabe deiner Personendaten verlangen. Wende dich dafür per E-Mail an mich.'],
                        'links' => [['label' => 'Eidgenössischer Datenschutz- und Öffentlichkeitsbeauftragter', 'url' => 'https://www.edoeb.admin.ch/de']],
                    ],
                ],
            ],
        ],
    ],
];
