<?php

return [
    'default_locale' => 'en',

    'locales' => [
        'en' => [
            'label' => 'EN',
            'name' => 'English',
        ],
        'de' => [
            'label' => 'DE',
            'name' => 'Deutsch',
        ],
    ],

    'socials' => [
        'email' => [
            'label' => 'Email',
            'display' => 'info@jeremylaederach.ch',
            'url' => 'mailto:info@jeremylaederach.ch',
        ],
        'github' => [
            'label' => 'GitHub',
            'display' => 'github.com/jeremylaederach',
            'url' => 'https://github.com/jeremylaederach',
        ],
        'linkedin' => [
            'label' => 'LinkedIn',
            'display' => 'Jeremy Läderach',
            'url' => 'https://www.linkedin.com/in/jeremy-l%C3%A4derach-816ab5326/',
        ],
    ],

    'content' => [
        'en' => [
            'meta' => [
                'title' => 'Jeremy Läderach',
                'description' => 'Personal portfolio of Jeremy Läderach, a software engineer building practical web systems with Laravel, .NET, and Angular.',
            ],
            'ui' => [
                'skip' => 'Skip to content',
                'language' => 'Language',
                'menu' => 'Primary navigation',
                'brand' => 'Jeremy Läderach home',
                'role' => 'Software Engineer',
                'open' => 'Open',
                'footer_navigation' => 'Explore',
                'back_to_top' => 'Back to top',
                'sound_mute' => 'Mute interface sounds',
                'sound_enable' => 'Enable interface sounds',
            ],
            'nav' => [
                ['label' => 'Home', 'route' => 'home', 'icon' => 'home'],
                ['label' => 'Projects', 'route' => 'projects', 'icon' => 'folder'],
                ['label' => 'About', 'route' => 'about', 'icon' => 'user'],
                ['label' => 'Contact', 'route' => 'contact', 'icon' => 'mail'],
            ],
            'home' => [
                'statement' => 'I build',
                'statement_accent' => 'useful digital systems.',
                'summary' => 'I build useful digital systems and thoughtful web experiences.',
                'explore' => 'Explore projects',
                'index_label' => 'Landing',
                'routes' => [
                    [
                        'label' => 'Projects',
                        'description' => 'Products, migrations, and client work.',
                        'route' => 'projects',
                    ],
                    [
                        'label' => 'About me',
                        'description' => 'Background, experience, and the tools behind my work.',
                        'route' => 'about',
                    ],
                    [
                        'label' => 'Contact',
                        'description' => 'A direct line for focused collaboration.',
                        'route' => 'contact',
                    ],
                ],
            ],
            'about_page' => [
                'eyebrow' => 'Profile',
                'heading' => 'About me',
                'intro' => 'I am a software engineer with a foundation in application development and a focus on full-stack systems that connect technology with real business needs.',
                'story_link' => 'My background',
                'story_heading' => 'Software with purpose, built from real requirements.',
                'body' => [
                    'As a passionate software engineer with a solid foundation gained through my apprenticeship as an Application Developer EFZ, I am focused on advancing my full-stack skills and bridging technology with business needs.',
                    'I enjoy analyzing complex requirements and turning them into purposeful, user-centered solutions. Clean architecture, maintainability, and thoughtful design guide the entire development process.',
                    'Looking ahead, I plan to study Business Informatics to deepen my understanding of how software can create real strategic value in business environments.',
                ],
                'technology_heading' => 'Tools I work with',
                'technology_label' => 'Toolkit',
                'technology_intro' => 'A focused toolkit for backend systems, structured interfaces, data, and dependable delivery.',
                'technology_list' => [
                    ['name' => '.NET / C#', 'detail' => 'ASP.NET Core · REST APIs', 'icon' => 'dotnet', 'fallback' => '.N', 'color' => '#8b5cf6'],
                    ['name' => 'Angular', 'detail' => 'Structured frontend applications', 'icon' => 'angular', 'fallback' => 'A', 'color' => '#dd0031'],
                    ['name' => 'TypeScript', 'detail' => 'Typed interface logic', 'icon' => 'typescript', 'fallback' => 'TS', 'color' => '#3178c6'],
                    ['name' => 'PostgreSQL', 'detail' => 'Relational data modelling', 'icon' => 'postgresql', 'fallback' => 'PG', 'color' => '#4169e1'],
                    ['name' => 'Git', 'detail' => 'Version control and delivery', 'icon' => 'git', 'fallback' => 'G', 'color' => '#f05032'],
                ],
                'career_heading' => 'Career path',
                'career_label' => 'Experience',
                'career' => [
                    [
                        'period' => '08 / 2019 – 08 / 2023',
                        'title' => 'Application Developer EFZ',
                        'body' => 'Apprenticeship in application development at EcoLogic AG in Zurich.',
                    ],
                    [
                        'period' => '08 / 2023 – 08 / 2024',
                        'title' => 'BMS',
                        'body' => 'Vocational baccalaureate with a focus on economics and business fundamentals in Zurich.',
                    ],
                    [
                        'period' => '08 / 2024 – Now',
                        'title' => 'Software Developer',
                        'body' => 'Professional software development experience alongside independent web solutions and software projects.',
                    ],
                    [
                        'period' => '09 / 2026 – 09 / 2030',
                        'title' => 'Business Informatics BSc',
                        'body' => 'Planned studies at OST to connect software engineering with business thinking and strategic value.',
                    ],
                ],
            ],
            'projects_page' => [
                'eyebrow' => 'Selected work',
                'featured_label' => 'Featured build',
                'secondary_label' => 'Additional work',
                'heading' => 'Projects',
                'intro' => 'Four current projects across product engineering, native desktop software, and web delivery.',
                'items' => [
                    [
                        'slug' => 'quantified',
                        'name' => 'Quantified',
                        'type' => 'Personal analytics product',
                        'description' => 'A full-stack product that turns Google Calendar activity into timelines, life-area dashboards, and useful personal context.',
                        'tags' => ['Angular', 'ASP.NET Core', 'PostgreSQL'],
                        'visual' => 'quantified',
                        'detail_route' => 'quantified',
                        'transition_theme' => 'quantified',
                    ],
                    [
                        'slug' => 'sessiondeck',
                        'name' => 'SessionDeck',
                        'type' => 'Native workspace launcher',
                        'description' => 'An open-source workspace launcher that starts reusable profiles of apps, commands, URLs, and folders with conservative process ownership.',
                        'tags' => ['WinUI 3', '.NET 10', 'MVVM'],
                        'visual' => 'image',
                        'image' => 'assets/work/sessiondeck-main.png',
                        'image_alt' => 'SessionDeck profile editor for a reusable development workspace',
                        'detail_route' => 'session-deck',
                        'transition_theme' => 'session-deck',
                    ],
                    [
                        'slug' => 'jay-jay-client-hub',
                        'name' => 'Jay-Jay Client Hub',
                        'type' => 'Bilingual customer portal',
                        'description' => 'A database-free Laravel prototype for clear project updates, private documents, direct requests, and customer information.',
                        'tags' => ['Laravel 13', 'Blade', 'Pest'],
                        'visual' => 'client-hub',
                        'detail_route' => 'jay-jay-client-hub',
                        'transition_theme' => 'client-hub',
                    ],
                    [
                        'slug' => 'jay-jay-web',
                        'name' => 'Jay-Jay Web',
                        'type' => 'Bilingual service website',
                        'description' => 'The Laravel and Blade source behind Jay-Jay, with localized pages, a static Plesk export, and tested contact delivery.',
                        'tags' => ['Laravel 13', 'Blade', 'Tailwind CSS'],
                        'visual' => 'image',
                        'image' => 'assets/work/jay-jay-home.png',
                        'image_alt' => 'Jay-Jay website landing page',
                        'detail_route' => 'jay-jay',
                        'transition_theme' => 'jay-jay',
                    ],
                ],
            ],
            'quantified_page' => [
                'slug' => 'quantified',
                'visual_type' => 'quantified',
                'meta_description' => 'Quantified is Jeremy Läderach\'s full-stack personal analytics platform built with Angular, ASP.NET Core, PostgreSQL, and Google Calendar.',
                'back' => 'All projects',
                'eyebrow' => 'Case study · Active build',
                'heading' => 'Quantified',
                'intro' => 'A personal analytics platform that gives calendar activity structure, context, and a useful place to look back.',
                'status_label' => 'Status',
                'status' => 'Active work in progress',
                'role_label' => 'Role',
                'role' => 'Product design and full-stack engineering',
                'preview_label' => 'Quantified analytics workspace',
                'preview' => [
                    'eyebrow' => 'Your personal data, connected',
                    'heading' => 'What would you like to understand?',
                    'body' => 'Start with Health or explore a pattern across your life.',
                    'status' => 'Health prototype',
                    'questions' => [
                        'How has my sleep changed?',
                        'What needs my attention?',
                        'How am I spending my time?',
                    ],
                    'composer' => 'Ask Quantified anything...',
                ],
                'overview' => [
                    'label' => '01 / Product',
                    'heading' => 'Calendar activity, turned into personal context.',
                    'body' => [
                        'Google Calendar is the input layer. Quantified imports tracker events, interprets category paths from their titles, and organizes the result across health, business, social, productivity, and chores.',
                        'The product is intentionally evolving in small, reviewable increments. Current work focuses on useful timelines and dashboards before adding more account or platform complexity.',
                    ],
                ],
                'architecture' => [
                    'label' => '02 / System',
                    'heading' => 'A focused full-stack pipeline.',
                    'items' => [
                        ['title' => 'Google Calendar', 'body' => 'OAuth and event ingestion provide the first real data source.'],
                        ['title' => 'ASP.NET Core', 'body' => 'The API parses category paths and serves domain-specific statistics.'],
                        ['title' => 'PostgreSQL', 'body' => 'EF Core persists the QFinances prototype and user-scoped records.'],
                        ['title' => 'Angular', 'body' => 'Feature views turn the data into timelines, dashboards, and reusable UI.'],
                    ],
                ],
                'scope' => [
                    'label' => '03 / Current scope',
                    'heading' => 'Built honestly, presented honestly.',
                    'intro' => 'Quantified is a working learning product, not a finished SaaS. These are the areas already taking shape.',
                    'items' => [
                        ['title' => 'QCalendar', 'body' => 'Calendar timeline, raw tracker events, and category-aware views.'],
                        ['title' => 'Life dashboards', 'body' => 'Dedicated Health, Business, and Social APIs and interfaces.'],
                        ['title' => 'QFinances', 'body' => 'A local PostgreSQL-backed finance prototype with basic user scoping.'],
                    ],
                ],
            ],
            'jay_jay_page' => [
                'slug' => 'jay-jay-web',
                'visual_type' => 'image',
                'visual_image' => 'assets/work/jay-jay-home.png',
                'preview_label' => 'Jay-Jay website landing page',
                'visual_kicker' => 'Production website',
                'visual_caption' => 'Laravel source · Static Plesk delivery',
                'meta_description' => 'Jay-Jay Web is a bilingual Laravel and Blade website with static export, responsive design, and a production contact workflow.',
                'back' => 'All projects',
                'eyebrow' => 'Case study · Live product',
                'heading' => 'Jay-Jay Web',
                'intro' => 'A bilingual service website with a maintainable Laravel source application and a deliberately simple production footprint.',
                'status_label' => 'Status',
                'status' => 'Live and maintained',
                'role_label' => 'Role',
                'role' => 'Design, engineering, and delivery',
                'overview' => [
                    'label' => '01 / Delivery model',
                    'heading' => 'A maintainable source app, delivered as a static website.',
                    'body' => [
                        'Jay-Jay presents websites, hosting, domains, email, and ongoing support for small Swiss organizations. The interface stays quiet and direct so the services remain understandable.',
                        'Laravel 13 and reusable Blade components keep the source structured. Production receives a generated static build plus a focused PHP contact endpoint, which fits the existing Plesk environment without carrying an unnecessary application runtime.',
                    ],
                ],
                'architecture' => [
                    'label' => '02 / Delivery pipeline',
                    'heading' => 'Framework ergonomics without deployment weight.',
                    'items' => [
                        ['title' => 'Laravel 13', 'body' => 'Localized routes, content composition, and the maintainable application source.'],
                        ['title' => 'Blade system', 'body' => 'Reusable navigation, cards, process flows, and calls to action.'],
                        ['title' => 'Static export', 'body' => 'Vite and a custom export command create the production-ready package.'],
                        ['title' => 'Plesk delivery', 'body' => 'A small validated PHP endpoint handles contact mail without a database.'],
                    ],
                ],
                'scope' => [
                    'label' => '03 / Product details',
                    'heading' => 'The calm interface is backed by deliberate engineering.',
                    'intro' => 'The visible website is simple by design. The implementation focuses on localization, dependable delivery, and an easy maintenance path.',
                    'items' => [
                        ['title' => 'Bilingual by default', 'body' => 'German-first pages have matching English routes, metadata, and error states.'],
                        ['title' => 'Contact delivery', 'body' => 'Origin checks, validation, a honeypot, timing checks, and rate limiting protect the public form.'],
                        ['title' => 'Quality gates', 'body' => 'Pest, Larastan, Pint, and the static production build run as repeatable checks.'],
                    ],
                ],
                'external_label' => 'Visit the live website',
                'external_url' => 'https://jay-jay.ch/en/',
            ],
            'sessiondeck_page' => [
                'slug' => 'sessiondeck',
                'visual_type' => 'image',
                'visual_image' => 'assets/work/sessiondeck-main.png',
                'preview_label' => 'SessionDeck profile editor with a reusable development workspace',
                'visual_kicker' => 'Windows desktop application',
                'visual_caption' => 'WinUI 3 · .NET 10 · Source-first MVP',
                'meta_description' => 'SessionDeck is an open-source WinUI 3 workspace launcher for reusable Windows session profiles.',
                'back' => 'All projects',
                'eyebrow' => 'Case study · Early MVP',
                'heading' => 'SessionDeck',
                'intro' => 'A native Windows application that opens a complete workspace from one reusable, intentionally configured profile.',
                'status_label' => 'Status',
                'status' => 'Functional source-build MVP',
                'role_label' => 'Role',
                'role' => 'Product design and Windows engineering',
                'overview' => [
                    'label' => '01 / Product',
                    'heading' => 'One action for a complete Windows workspace.',
                    'body' => [
                        'SessionDeck is for developers, gamers, and power users who repeatedly open the same applications, commands, URLs, and folders. Profiles make that setup reusable and explicit.',
                        'The MVP prioritizes a predictable local workflow over cloud features. It has no telemetry, account, administrator requirement, or automatic command execution, and it stores readable versioned JSON in per-user application data.',
                    ],
                ],
                'architecture' => [
                    'label' => '02 / Architecture',
                    'heading' => 'Windows-specific behavior behind clear boundaries.',
                    'items' => [
                        ['title' => 'Core', 'body' => 'Domain models, profile validation, and contracts without a WinUI dependency.'],
                        ['title' => 'Infrastructure', 'body' => 'JSON persistence, process launching, runtime inspection, and safe stopping.'],
                        ['title' => 'Desktop', 'body' => 'WinUI 3 views, MVVM view models, and dependency-injection composition.'],
                        ['title' => 'Tests', 'body' => 'xUnit coverage for validation, persistence, migrations, and process ownership.'],
                    ],
                ],
                'scope' => [
                    'label' => '03 / Safety model',
                    'heading' => 'A failed stop is better than stopping the wrong process.',
                    'intro' => 'Process ownership is intentionally conservative. SessionDeck only stops processes it can prove were started by the current in-memory run.',
                    'items' => [
                        ['title' => 'Reusable profiles', 'body' => 'Ordered launch items support applications, commands, URLs, folders, delays, and enabled state.'],
                        ['title' => 'Sequential results', 'body' => 'Every enabled item launches in order and reports its own success or validation failure.'],
                        ['title' => 'Conservative ownership', 'body' => 'Exact-path detection is informational; existing processes are never adopted or terminated.'],
                    ],
                ],
                'external_label' => 'View the GitHub repository',
                'external_url' => 'https://github.com/jeremylaederach/session-deck',
            ],
            'client_hub_page' => [
                'slug' => 'jay-jay-client-hub',
                'visual_type' => 'client-hub',
                'meta_description' => 'Jay-Jay Client Hub is a bilingual Laravel prototype for project updates, customer documents, and direct support requests.',
                'back' => 'All projects',
                'eyebrow' => 'Case study · Interactive prototype',
                'heading' => 'Jay-Jay Client Hub',
                'intro' => 'A focused customer portal prototype that keeps project status, documents, requests, and company information in one calm workspace.',
                'status_label' => 'Status',
                'status' => 'Interactive prototype ready for review',
                'role_label' => 'Role',
                'role' => 'Product design, UX architecture, and Laravel engineering',
                'preview_label' => 'Jay-Jay Client Hub customer overview',
                'preview' => [
                    'badge' => 'Interactive prototype',
                    'navigation' => ['Overview', 'Projects', 'Documents'],
                    'eyebrow' => 'Client area',
                    'heading' => 'Welcome, Anna.',
                    'body' => 'Projects, important documents, and the next steps in one place.',
                    'customer' => ['initials' => 'AE', 'name' => 'Anna Example', 'company' => 'Demo Company'],
                    'cards' => [
                        ['label' => 'Current projects', 'value' => '02', 'meta' => 'Next steps are visible'],
                        ['label' => 'Recent documents', 'value' => '03', 'meta' => 'Prepared for secure storage'],
                        ['label' => 'Open requests', 'value' => '02', 'meta' => 'Direct, without help-desk theatre'],
                    ],
                ],
                'overview' => [
                    'label' => '01 / Product direction',
                    'heading' => 'Customer clarity before account complexity.',
                    'body' => [
                        'The Client Hub is intentionally separate from the public Jay-Jay website. It is designed for the private information that will later require authentication, customer authorization, secure files, and its own release cycle.',
                        'The current application is an honest, database-free prototype. Every visible person, company, project, document, and request uses demonstration data, and no form submission is stored or sent.',
                    ],
                ],
                'architecture' => [
                    'label' => '02 / Prototype architecture',
                    'heading' => 'Real application structure without premature infrastructure.',
                    'items' => [
                        ['title' => 'Laravel 13', 'body' => 'Localized routes, controllers, middleware, and the production-shaped application boundary.'],
                        ['title' => 'Prototype data service', 'body' => 'One replaceable service keeps demonstration content out of controllers and templates.'],
                        ['title' => 'Blade interface', 'body' => 'Reusable navigation, project, document, status, and form components.'],
                        ['title' => 'Quality gates', 'body' => 'Pest, Larastan, Pint, and the Vite build cover both locales and prototype behavior.'],
                    ],
                ],
                'scope' => [
                    'label' => '03 / Demonstrated workflows',
                    'heading' => 'Enough product to review the decisions that matter.',
                    'intro' => 'The prototype makes the customer-facing information architecture tangible while deferring sensitive infrastructure until the product direction is approved.',
                    'items' => [
                        ['title' => 'Project timelines', 'body' => 'Current state, next step, responsibility, milestones, and chronological updates stay easy to scan.'],
                        ['title' => 'Document library', 'body' => 'The interface demonstrates future private files while downloads remain deliberately disabled.'],
                        ['title' => 'Direct requests', 'body' => 'A bilingual validated form demonstrates feedback without pretending to persist or deliver messages.'],
                    ],
                ],
            ],
            'contact_page' => [
                'eyebrow' => 'Start a conversation',
                'heading' => 'Contact',
                'intro' => 'Email is the best first step. Send the rough goal, links, constraints, and what a good outcome should feel like.',
                'direct_label' => 'Write directly',
                'direct_heading' => 'Tell me what you want to build.',
                'context_label' => 'A useful first note',
                'context' => 'A short outline of the goal, timing, and relevant links is enough. I will reply with the next useful steps.',
                'channels_label' => 'Elsewhere',
            ],
            'not_found' => [
                'eyebrow' => 'Lost route',
                'heading' => 'Page not found',
                'intro' => 'The address does not lead anywhere, but the rest of the portfolio is right where it should be.',
                'action' => 'Back to home',
            ],
            'imprint' => [
                'title' => 'Imprint',
                'intro' => 'Legal and ownership details for this personal portfolio.',
                'sections' => [
                    ['title' => 'Responsible for content', 'body' => ['Jeremy Läderach', 'Switzerland']],
                    ['title' => 'Contact', 'body' => ['info@jeremylaederach.ch']],
                    ['title' => 'Note', 'body' => ['This Laravel prototype keeps the legal page intentionally compact. Additional business address or privacy details can be added before production launch.']],
                ],
            ],
        ],

        'de' => [
            'meta' => [
                'title' => 'Jeremy Läderach',
                'description' => 'Persönliches Portfolio von Jeremy Läderach, einem Softwareentwickler mit Fokus auf praktische Websysteme mit Laravel, .NET und Angular.',
            ],
            'ui' => [
                'skip' => 'Zum Inhalt springen',
                'language' => 'Sprache',
                'menu' => 'Hauptnavigation',
                'brand' => 'Jeremy Läderach Startseite',
                'role' => 'Softwareentwickler',
                'open' => 'Öffnen',
                'footer_navigation' => 'Entdecken',
                'back_to_top' => 'Nach oben',
                'sound_mute' => 'Interface-Töne ausschalten',
                'sound_enable' => 'Interface-Töne einschalten',
            ],
            'nav' => [
                ['label' => 'Start', 'route' => 'home', 'icon' => 'home'],
                ['label' => 'Projekte', 'route' => 'projects', 'icon' => 'folder'],
                ['label' => 'Profil', 'route' => 'about', 'icon' => 'user'],
                ['label' => 'Kontakt', 'route' => 'contact', 'icon' => 'mail'],
            ],
            'home' => [
                'statement' => 'Ich entwickle',
                'statement_accent' => 'nützliche digitale Systeme.',
                'summary' => 'Ich entwickle nützliche digitale Systeme und durchdachte Web-Erlebnisse.',
                'explore' => 'Projekte entdecken',
                'index_label' => 'Start',
                'routes' => [
                    [
                        'label' => 'Projekte',
                        'description' => 'Produkte, Migrationen und Kundenprojekte.',
                        'route' => 'projects',
                    ],
                    [
                        'label' => 'Über mich',
                        'description' => 'Hintergrund, Erfahrung und die Technologien hinter meiner Arbeit.',
                        'route' => 'about',
                    ],
                    [
                        'label' => 'Kontakt',
                        'description' => 'Der direkte Weg für eine fokussierte Zusammenarbeit.',
                        'route' => 'contact',
                    ],
                ],
            ],
            'about_page' => [
                'eyebrow' => 'Profil',
                'heading' => 'Über mich',
                'intro' => 'Ich bin Softwareentwickler mit fundierter Ausbildung in der Applikationsentwicklung. Mein Fokus liegt auf Full-Stack-Systemen, die technische Möglichkeiten mit konkreten Geschäftsanforderungen verbinden.',
                'story_link' => 'Mein Weg',
                'story_heading' => 'Software mit klarem Zweck, entwickelt aus konkreten Anforderungen.',
                'body' => [
                    'Durch meine EFZ-Lehre als Applikationsentwickler habe ich eine solide technische Grundlage aufgebaut. Heute vertiefe ich meine Full-Stack-Kompetenzen und verbinde Softwareentwicklung mit wirtschaftlichem Verständnis.',
                    'Komplexe Anforderungen zerlege ich in klare, nutzerorientierte Lösungen. Saubere Architektur, Wartbarkeit und durchdachtes Design prägen dabei den gesamten Entwicklungsprozess.',
                    'Als Nächstes plane ich ein Studium in Wirtschaftsinformatik, um technische Entscheidungen noch stärker mit strategischem Mehrwert für Unternehmen zu verbinden.',
                ],
                'technology_heading' => 'Technologien, mit denen ich arbeite',
                'technology_label' => 'Tools',
                'technology_intro' => 'Eine fokussierte Auswahl für Backend-Systeme, strukturierte Oberflächen, Daten und zuverlässige Auslieferung.',
                'technology_list' => [
                    ['name' => '.NET / C#', 'detail' => 'ASP.NET Core · REST APIs', 'icon' => 'dotnet', 'fallback' => '.N', 'color' => '#8b5cf6'],
                    ['name' => 'Angular', 'detail' => 'Strukturierte Frontend-Anwendungen', 'icon' => 'angular', 'fallback' => 'A', 'color' => '#dd0031'],
                    ['name' => 'TypeScript', 'detail' => 'Typsichere Frontend-Logik', 'icon' => 'typescript', 'fallback' => 'TS', 'color' => '#3178c6'],
                    ['name' => 'PostgreSQL', 'detail' => 'Relationale Datenmodellierung', 'icon' => 'postgresql', 'fallback' => 'PG', 'color' => '#4169e1'],
                    ['name' => 'Git', 'detail' => 'Versionskontrolle und Auslieferung', 'icon' => 'git', 'fallback' => 'G', 'color' => '#f05032'],
                ],
                'career_heading' => 'Werdegang',
                'career_label' => 'Erfahrung',
                'career' => [
                    [
                        'period' => '08 / 2019 – 08 / 2023',
                        'title' => 'Applikationsentwickler EFZ',
                        'body' => 'Lehre in Applikationsentwicklung bei der EcoLogic AG in Zürich.',
                    ],
                    [
                        'period' => '08 / 2023 – 08 / 2024',
                        'title' => 'BMS',
                        'body' => 'Berufsmaturität mit Schwerpunkt Wirtschaft in Zürich.',
                    ],
                    [
                        'period' => '08 / 2024 – Heute',
                        'title' => 'Softwareentwickler',
                        'body' => 'Berufserfahrung in der Softwareentwicklung sowie Arbeit an eigenen Weblösungen und Softwareprojekten.',
                    ],
                    [
                        'period' => '09 / 2026 – 09 / 2030',
                        'title' => 'BSc Wirtschaftsinformatik',
                        'body' => 'Geplantes Studium an der OST, um Softwareentwicklung mit wirtschaftlichem Denken und strategischem Nutzen zu verbinden.',
                    ],
                ],
            ],
            'projects_page' => [
                'eyebrow' => 'Ausgewählte Arbeiten',
                'featured_label' => 'Hauptprojekt',
                'secondary_label' => 'Weitere Arbeiten',
                'heading' => 'Projekte',
                'intro' => 'Vier aktuelle Projekte aus Produktentwicklung, nativer Desktop-Software und Web-Delivery.',
                'items' => [
                    [
                        'slug' => 'quantified',
                        'name' => 'Quantified',
                        'type' => 'Persönliches Analyseprodukt',
                        'description' => 'Ein Full-Stack-Produkt, das Google-Calendar-Aktivitäten in Timelines, Lebensbereich-Dashboards und nützlichen persönlichen Kontext übersetzt.',
                        'tags' => ['Angular', 'ASP.NET Core', 'PostgreSQL'],
                        'visual' => 'quantified',
                        'detail_route' => 'quantified',
                        'transition_theme' => 'quantified',
                    ],
                    [
                        'slug' => 'sessiondeck',
                        'name' => 'SessionDeck',
                        'type' => 'Nativer Workspace-Launcher',
                        'description' => 'Ein Open-Source Workspace Launcher für wiederverwendbare Profile aus Apps, Commands, URLs und Ordnern mit bewusst sicherem Prozess-Ownership.',
                        'tags' => ['WinUI 3', '.NET 10', 'MVVM'],
                        'visual' => 'image',
                        'image' => 'assets/work/sessiondeck-main.png',
                        'image_alt' => 'SessionDeck Profileditor für einen wiederverwendbaren Development Workspace',
                        'detail_route' => 'session-deck',
                        'transition_theme' => 'session-deck',
                    ],
                    [
                        'slug' => 'jay-jay-client-hub',
                        'name' => 'Jay-Jay Client Hub',
                        'type' => 'Zweisprachiges Kundenportal',
                        'description' => 'Ein datenbankfreier Laravel-Prototyp für klare Projektstände, private Dokumente, direkte Anfragen und Kundendaten.',
                        'tags' => ['Laravel 13', 'Blade', 'Pest'],
                        'visual' => 'client-hub',
                        'detail_route' => 'jay-jay-client-hub',
                        'transition_theme' => 'client-hub',
                    ],
                    [
                        'slug' => 'jay-jay-web',
                        'name' => 'Jay-Jay Web',
                        'type' => 'Zweisprachige Service-Website',
                        'description' => 'Die Laravel- und Blade-Basis von Jay-Jay mit lokalisierten Seiten, statischem Plesk-Export und getesteter Kontaktzustellung.',
                        'tags' => ['Laravel 13', 'Blade', 'Tailwind CSS'],
                        'visual' => 'image',
                        'image' => 'assets/work/jay-jay-home.png',
                        'image_alt' => 'Startseite der Jay-Jay Website',
                        'detail_route' => 'jay-jay',
                        'transition_theme' => 'jay-jay',
                    ],
                ],
            ],
            'quantified_page' => [
                'slug' => 'quantified',
                'visual_type' => 'quantified',
                'meta_description' => 'Quantified ist Jeremy Läderachs persönliche Full-Stack-Analytics-Plattform mit Angular, ASP.NET Core, PostgreSQL und Google Calendar.',
                'back' => 'Alle Projekte',
                'eyebrow' => 'Case Study · In Entwicklung',
                'heading' => 'Quantified',
                'intro' => 'Eine persönliche Analytics-Plattform, die Kalenderaktivitäten strukturiert, einordnet und rückblickend verständlich macht.',
                'status_label' => 'Status',
                'status' => 'Aktiv in Entwicklung',
                'role_label' => 'Rolle',
                'role' => 'Product Design und Full-Stack-Entwicklung',
                'preview_label' => 'Quantified Analytics Workspace',
                'preview' => [
                    'eyebrow' => 'Your personal data, connected',
                    'heading' => 'What would you like to understand?',
                    'body' => 'Start with Health or explore a pattern across your life.',
                    'status' => 'Health prototype',
                    'questions' => [
                        'How has my sleep changed?',
                        'What needs my attention?',
                        'How am I spending my time?',
                    ],
                    'composer' => 'Ask Quantified anything...',
                ],
                'overview' => [
                    'label' => '01 / Produkt',
                    'heading' => 'Kalenderaktivität wird zu persönlichem Kontext.',
                    'body' => [
                        'Google Calendar ist die erste Datenquelle. Quantified importiert Tracker-Events, interpretiert Kategoriepfade aus ihren Titeln und ordnet die Resultate Gesundheit, Business, Sozialem, Produktivität und Haushalt zu.',
                        'Das Produkt wächst bewusst in kleinen, überprüfbaren Schritten. Aktuell stehen nützliche Timelines und Dashboards im Fokus, bevor zusätzliche Account- oder Plattform-Komplexität dazukommt.',
                    ],
                ],
                'architecture' => [
                    'label' => '02 / System',
                    'heading' => 'Eine fokussierte Full-Stack-Pipeline.',
                    'items' => [
                        ['title' => 'Google Calendar', 'body' => 'OAuth und Event-Import liefern die erste reale Datenquelle.'],
                        ['title' => 'ASP.NET Core', 'body' => 'Die API analysiert Kategoriepfade und liefert domänenspezifische Statistiken.'],
                        ['title' => 'PostgreSQL', 'body' => 'EF Core persistiert den QFinances-Prototyp und benutzerbezogene Daten.'],
                        ['title' => 'Angular', 'body' => 'Feature Views übersetzen die Daten in Timelines, Dashboards und wiederverwendbare UI.'],
                    ],
                ],
                'scope' => [
                    'label' => '03 / Aktueller Stand',
                    'heading' => 'Ehrlich entwickelt, ehrlich präsentiert.',
                    'intro' => 'Quantified ist ein funktionierendes Lernprodukt, noch kein fertiges SaaS. Diese Bereiche nehmen bereits konkrete Form an.',
                    'items' => [
                        ['title' => 'QCalendar', 'body' => 'Kalender-Timeline, rohe Tracker-Events und kategoriebasierte Ansichten.'],
                        ['title' => 'Life Dashboards', 'body' => 'Eigene APIs und Oberflächen für Health, Business und Social.'],
                        ['title' => 'QFinances', 'body' => 'Ein lokaler PostgreSQL-Prototyp mit grundlegender Benutzerzuordnung.'],
                    ],
                ],
            ],
            'jay_jay_page' => [
                'slug' => 'jay-jay-web',
                'visual_type' => 'image',
                'visual_image' => 'assets/work/jay-jay-home.png',
                'preview_label' => 'Startseite der Jay-Jay Website',
                'visual_kicker' => 'Produktive Website',
                'visual_caption' => 'Laravel-Quelle · Statische Plesk-Auslieferung',
                'meta_description' => 'Jay-Jay Web ist eine zweisprachige Laravel- und Blade-Website mit statischem Export, responsivem Design und produktiver Kontaktzustellung.',
                'back' => 'Alle Projekte',
                'eyebrow' => 'Case Study · Live-Produkt',
                'heading' => 'Jay-Jay Web',
                'intro' => 'Eine zweisprachige Service-Website mit einer wartbaren Laravel-Quellanwendung und bewusst schlankem Produktionsbetrieb.',
                'status_label' => 'Status',
                'status' => 'Live und in Betreuung',
                'role_label' => 'Rolle',
                'role' => 'Design, Entwicklung und Auslieferung',
                'overview' => [
                    'label' => '01 / Delivery-Modell',
                    'heading' => 'Eine wartbare Quellanwendung, ausgeliefert als statische Website.',
                    'body' => [
                        'Jay-Jay präsentiert Websites, Hosting, Domains, E-Mail und laufende Betreuung für kleine Schweizer Organisationen. Die Oberfläche bleibt ruhig und direkt, damit die Leistungen verständlich bleiben.',
                        'Laravel 13 und wiederverwendbare Blade-Komponenten strukturieren den Quellcode. In Produktion landet ein generierter statischer Build mit einem fokussierten PHP-Kontaktendpunkt – passend zur bestehenden Plesk-Umgebung, ohne unnötige Application Runtime.',
                    ],
                ],
                'architecture' => [
                    'label' => '02 / Delivery-Pipeline',
                    'heading' => 'Framework-Ergonomie ohne unnötiges Deployment-Gewicht.',
                    'items' => [
                        ['title' => 'Laravel 13', 'body' => 'Lokalisierte Routen, Content-Komposition und die wartbare Quellanwendung.'],
                        ['title' => 'Blade-System', 'body' => 'Wiederverwendbare Navigation, Karten, Prozessabläufe und Calls to Action.'],
                        ['title' => 'Static Export', 'body' => 'Vite und ein eigener Export-Command erzeugen das produktionsfertige Paket.'],
                        ['title' => 'Plesk Delivery', 'body' => 'Ein kleiner validierter PHP-Endpunkt versendet Kontaktanfragen ohne Datenbank.'],
                    ],
                ],
                'scope' => [
                    'label' => '03 / Produktdetails',
                    'heading' => 'Hinter der ruhigen Oberfläche steckt bewusste Engineering-Arbeit.',
                    'intro' => 'Die sichtbare Website ist absichtlich einfach. Die Implementierung konzentriert sich auf Lokalisierung, verlässliche Auslieferung und gute Wartbarkeit.',
                    'items' => [
                        ['title' => 'Zweisprachig ab Basis', 'body' => 'Deutschsprachige Seiten besitzen passende englische Routen, Metadaten und Fehlerseiten.'],
                        ['title' => 'Kontaktzustellung', 'body' => 'Origin-Prüfung, Validierung, Honeypot, Mindestdauer und Rate Limiting schützen das öffentliche Formular.'],
                        ['title' => 'Quality Gates', 'body' => 'Pest, Larastan, Pint und der statische Produktions-Build laufen als wiederholbare Prüfungen.'],
                    ],
                ],
                'external_label' => 'Live-Website besuchen',
                'external_url' => 'https://jay-jay.ch/de/',
            ],
            'sessiondeck_page' => [
                'slug' => 'sessiondeck',
                'visual_type' => 'image',
                'visual_image' => 'assets/work/sessiondeck-main.png',
                'preview_label' => 'SessionDeck Profileditor mit einem wiederverwendbaren Development Workspace',
                'visual_kicker' => 'Windows-Desktop-Anwendung',
                'visual_caption' => 'WinUI 3 · .NET 10 · Source-first MVP',
                'meta_description' => 'SessionDeck ist ein Open-Source WinUI-3-Workspace-Launcher für wiederverwendbare Windows-Session-Profile.',
                'back' => 'Alle Projekte',
                'eyebrow' => 'Case Study · Früher MVP',
                'heading' => 'SessionDeck',
                'intro' => 'Eine native Windows-Anwendung, die einen vollständigen Workspace aus einem wiederverwendbaren, bewusst konfigurierten Profil öffnet.',
                'status_label' => 'Status',
                'status' => 'Funktionaler Source-Build MVP',
                'role_label' => 'Rolle',
                'role' => 'Product Design und Windows-Entwicklung',
                'overview' => [
                    'label' => '01 / Produkt',
                    'heading' => 'Eine Aktion für einen vollständigen Windows-Workspace.',
                    'body' => [
                        'SessionDeck richtet sich an Entwickler, Gamer und Power User, die wiederholt dieselben Anwendungen, Commands, URLs und Ordner öffnen. Profile machen dieses Setup wiederverwendbar und explizit.',
                        'Der MVP priorisiert einen vorhersehbaren lokalen Workflow statt Cloud-Funktionen. Er hat keine Telemetrie, Accounts, Administrator-Anforderung oder automatische Command-Ausführung und speichert lesbares, versioniertes JSON in den benutzerspezifischen App-Daten.',
                    ],
                ],
                'architecture' => [
                    'label' => '02 / Architektur',
                    'heading' => 'Windows-spezifisches Verhalten hinter klaren Grenzen.',
                    'items' => [
                        ['title' => 'Core', 'body' => 'Domain-Modelle, Profilvalidierung und Contracts ohne WinUI-Abhängigkeit.'],
                        ['title' => 'Infrastructure', 'body' => 'JSON-Persistenz, Prozessstart, Runtime-Inspektion und sicheres Stoppen.'],
                        ['title' => 'Desktop', 'body' => 'WinUI-3-Views, MVVM View Models und Dependency-Injection-Komposition.'],
                        ['title' => 'Tests', 'body' => 'xUnit-Coverage für Validierung, Persistenz, Migrationen und Prozess-Ownership.'],
                    ],
                ],
                'scope' => [
                    'label' => '03 / Sicherheitsmodell',
                    'heading' => 'Ein fehlgeschlagener Stopp ist besser als der falsche Prozess.',
                    'intro' => 'Process-Ownership ist bewusst konservativ. SessionDeck stoppt nur Prozesse, die nachweislich vom aktuellen In-Memory-Run gestartet wurden.',
                    'items' => [
                        ['title' => 'Wiederverwendbare Profile', 'body' => 'Geordnete Launch Items unterstützen Apps, Commands, URLs, Ordner, Delays und Enabled State.'],
                        ['title' => 'Sequenzielle Resultate', 'body' => 'Jedes aktivierte Element startet der Reihe nach und meldet Erfolg oder Validierungsfehler separat.'],
                        ['title' => 'Sicheres Ownership', 'body' => 'Exact-Path Detection ist nur informativ; bestehende Prozesse werden nie übernommen oder beendet.'],
                    ],
                ],
                'external_label' => 'GitHub-Repository ansehen',
                'external_url' => 'https://github.com/jeremylaederach/session-deck',
            ],
            'client_hub_page' => [
                'slug' => 'jay-jay-client-hub',
                'visual_type' => 'client-hub',
                'meta_description' => 'Jay-Jay Client Hub ist ein zweisprachiger Laravel-Prototyp für Projektstände, Kundendokumente und direkte Anfragen.',
                'back' => 'Alle Projekte',
                'eyebrow' => 'Case Study · Interaktiver Prototyp',
                'heading' => 'Jay-Jay Client Hub',
                'intro' => 'Ein fokussierter Kundenportal-Prototyp, der Projektstände, Dokumente, Anfragen und Unternehmensdaten in einem ruhigen Workspace bündelt.',
                'status_label' => 'Status',
                'status' => 'Interaktiver Prototyp bereit für Review',
                'role_label' => 'Rolle',
                'role' => 'Product Design, UX-Architektur und Laravel-Entwicklung',
                'preview_label' => 'Kundenübersicht im Jay-Jay Client Hub',
                'preview' => [
                    'badge' => 'Interaktiver Prototyp',
                    'navigation' => ['Übersicht', 'Projekte', 'Dokumente'],
                    'eyebrow' => 'Kundenbereich',
                    'heading' => 'Willkommen, Anna.',
                    'body' => 'Projekte, wichtige Dokumente und die nächsten Schritte an einem Ort.',
                    'customer' => ['initials' => 'AM', 'name' => 'Anna Muster', 'company' => 'Demo-Unternehmen'],
                    'cards' => [
                        ['label' => 'Laufende Projekte', 'value' => '02', 'meta' => 'Nächste Schritte sind sichtbar'],
                        ['label' => 'Neue Dokumente', 'value' => '03', 'meta' => 'Für sichere Ablage vorbereitet'],
                        ['label' => 'Offene Anfragen', 'value' => '02', 'meta' => 'Direkt, ohne Ticketsystem-Show'],
                    ],
                ],
                'overview' => [
                    'label' => '01 / Produktrichtung',
                    'heading' => 'Klarheit für Kunden vor Account-Komplexität.',
                    'body' => [
                        'Der Client Hub ist bewusst von der öffentlichen Jay-Jay Website getrennt. Er ist für private Informationen gedacht, die später Anmeldung, Kundenberechtigungen, sichere Dateien und einen eigenen Release-Zyklus benötigen.',
                        'Die aktuelle Anwendung ist ein ehrlicher, datenbankfreier Prototyp. Alle sichtbaren Personen, Unternehmen, Projekte, Dokumente und Anfragen verwenden Beispieldaten; Formulare werden weder gespeichert noch versendet.',
                    ],
                ],
                'architecture' => [
                    'label' => '02 / Prototyp-Architektur',
                    'heading' => 'Reale Anwendungsstruktur ohne vorschnelle Infrastruktur.',
                    'items' => [
                        ['title' => 'Laravel 13', 'body' => 'Lokalisierte Routen, Controller, Middleware und eine produktionsnahe Anwendungsgrenze.'],
                        ['title' => 'Prototype Data Service', 'body' => 'Ein austauschbarer Service hält Beispieldaten aus Controllern und Templates heraus.'],
                        ['title' => 'Blade Interface', 'body' => 'Wiederverwendbare Navigation, Projekt-, Dokument-, Status- und Formularkomponenten.'],
                        ['title' => 'Quality Gates', 'body' => 'Pest, Larastan, Pint und der Vite-Build prüfen beide Sprachen und das Prototyp-Verhalten.'],
                    ],
                ],
                'scope' => [
                    'label' => '03 / Gezeigte Abläufe',
                    'heading' => 'Genug Produkt, um die wichtigen Entscheidungen zu prüfen.',
                    'intro' => 'Der Prototyp macht die kundenorientierte Informationsarchitektur greifbar und verschiebt sensible Infrastruktur, bis die Produktrichtung bestätigt ist.',
                    'items' => [
                        ['title' => 'Projektverläufe', 'body' => 'Status, nächster Schritt, Zuständigkeit, Etappen und chronologische Updates bleiben schnell erfassbar.'],
                        ['title' => 'Dokumentbibliothek', 'body' => 'Die Oberfläche zeigt die spätere private Ablage; Downloads bleiben bewusst deaktiviert.'],
                        ['title' => 'Direkte Anfragen', 'body' => 'Ein zweisprachiges validiertes Formular demonstriert Feedback, ohne Speicherung oder Versand vorzutäuschen.'],
                    ],
                ],
            ],
            'contact_page' => [
                'eyebrow' => 'Gespräch beginnen',
                'heading' => 'Kontakt',
                'intro' => 'E-Mail ist der beste erste Schritt. Schick mir dein Ziel, relevante Links und die wichtigsten Rahmenbedingungen.',
                'direct_label' => 'Direkt schreiben',
                'direct_heading' => 'Erzähl mir, was du umsetzen möchtest.',
                'context_label' => 'Für einen guten Start',
                'context' => 'Ein kurzer Überblick über Ziel, Zeitrahmen und relevante Links reicht. Ich melde mich mit den nächsten sinnvollen Schritten.',
                'channels_label' => 'Weitere Profile',
            ],
            'not_found' => [
                'eyebrow' => 'Falscher Weg',
                'heading' => 'Seite nicht gefunden',
                'intro' => 'Diese Adresse führt nirgendwohin. Der Rest des Portfolios ist aber genau dort, wo er sein soll.',
                'action' => 'Zurück zur Startseite',
            ],
            'imprint' => [
                'title' => 'Impressum',
                'intro' => 'Rechtliche Angaben zu diesem persönlichen Portfolio.',
                'sections' => [
                    ['title' => 'Verantwortlich für den Inhalt', 'body' => ['Jeremy Läderach', 'Schweiz']],
                    ['title' => 'Kontakt', 'body' => ['info@jeremylaederach.ch']],
                    ['title' => 'Hinweis', 'body' => ['Dieser Laravel-Prototyp hält die rechtliche Seite bewusst kompakt. Angaben zur Geschäftsadresse und zum Datenschutz können vor dem Produktionsstart ergänzt werden.']],
                ],
            ],
        ],
    ],
];
